import {
  BATTERY,
  Battery,
  CommonDigitalTwinsParameter,
  CommonSystemParameter,
  DiagramVariableType,
  InputType,
  SolarPanel,
  WindTurbine,
} from './common';

export enum OperationModeType {
  Mode1 = 'Paneles individuales',
  Mode2 = 'Paneles en serie',
  Mode3 = 'Paneles en paralelo',
  Mode4 = 'Aerogenerador',
  Mode5 = 'Paneles y aerogenerador',
}

export type SolarWindParameters = CommonSystemParameter &
  CommonDigitalTwinsParameter & {
    inputOperationMode: OperationModeType;
    monocrystallinePanel: SolarPanel;
    policrystallinePanel: SolarPanel;
    flexPanel: SolarPanel;
    cadmiumTelluridePanel: SolarPanel;
    windTurbine: WindTurbine;
    battery1: Battery;
    battery2: Battery;
  };

const MONOCRYSTALLINE_PANEL: SolarPanel = {
  isConnected: true,
  peakPower: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  deratingFactor: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  efficiency: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  nominalIrradiance: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  testIrradiance: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  nominalTemperature: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  testTemperature: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  operatingTemperature: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  temperatureVariationCoefficient: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
};

const POLICRYSTALLINE_PANEL: SolarPanel = {
  isConnected: true,
  peakPower: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  deratingFactor: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  efficiency: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  nominalIrradiance: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  testIrradiance: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  nominalTemperature: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  testTemperature: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  operatingTemperature: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  temperatureVariationCoefficient: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
};

const FLEX_PANEL: SolarPanel = {
  isConnected: true,
  peakPower: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  deratingFactor: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  efficiency: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  nominalIrradiance: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  testIrradiance: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  nominalTemperature: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  testTemperature: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  operatingTemperature: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  temperatureVariationCoefficient: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
};

const CADMIUM_TELLURIDE_PANEL: SolarPanel = {
  isConnected: true,
  peakPower: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  deratingFactor: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  efficiency: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  nominalIrradiance: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  testIrradiance: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  nominalTemperature: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  testTemperature: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  operatingTemperature: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  temperatureVariationCoefficient: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
};

const WIND_TURBINE: WindTurbine = {
  peakPower: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  rotorHeight: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  anemometerHeight: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  ratedWindSpeed: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  lowerCutoffWindSpeed: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
  upperCutoffWindSpeed: {
    disabled: false,
    value: 0,
    tooltip: '',
    unit: '',
    variableString: '',
    variableSubString: undefined,
    min: undefined,
    max: undefined,
    step: undefined,
  },
};

export const SOLAR_PANEL: SolarWindParameters = {
  name: 'Nombre',
  timeMultiplier: {
    disabled: false,
    value: 1,
    tooltip: 'Multiplicador de tiempo',
    unit: '',
    variableString: '',
    min: 1,
    max: 10,
  },
  inputOfflineOperation: true,
  inputOperationMode: OperationModeType.Mode1,
  monocrystallinePanel: MONOCRYSTALLINE_PANEL,
  policrystallinePanel: POLICRYSTALLINE_PANEL,
  flexPanel: FLEX_PANEL,
  cadmiumTelluridePanel: CADMIUM_TELLURIDE_PANEL,
  windTurbine: WIND_TURBINE,
  battery1: BATTERY,
  battery2: BATTERY,
};

export const SOLAR_DIAGRAM_VARIABLES: DiagramVariableType[] = [];
