import Constants from '../../config/constants';
import {
  CommonSystemParameter,
  MONOCRYSTALLINE_PANEL as MP,
  POLICRYSTALLINE_PANEL as PP,
  FLEX_PANEL as FP,
  CADMIUM_TELLURIDE_PANEL as CTP,
  WIND_TURBINE,
  StepUnitType,
} from '../common';
import { CommonChartType } from '../graph';
import { InputArrayType, InputType } from '../inputType';
import {
  Battery,
  CommonController,
  CommonDigitalTwinsParameter,
  DiagramVariableType,
  Inverter,
  InverterHybrid,
  IsConnected,
  SolarPanel,
  WindTurbine,
} from './common';

export enum OperationModeType {
  Mode1 = 'Mode1',
  Mode3 = 'Mode3',
  Mode2 = 'Mode2',
  Mode4 = 'Mode4',
  Mode5 = 'Mode5',
}

export enum OperationModeText {
  Mode1 = 'Paneles individuales',
  Mode3 = 'Paneles en paralelo',
  Mode2 = 'Paneles en serie',
  Mode4 = 'Aerogenerador',
  Mode5 = 'Paneles y aerogenerador',
}

export type SolarWindParameters = CommonSystemParameter &
  CommonDigitalTwinsParameter & {
    isBatteryConnected: boolean;
    inputOperationMode: OperationModeType;
    lampsHeight: number;
    panelsAngle: InputType;
    monocrystallinePanel: SolarPanel;
    policrystallinePanel: SolarPanel;
    flexPanel: SolarPanel;
    cadmiumTelluridePanel: SolarPanel;
    windTurbine: WindTurbine;
    battery1: Battery;
    isBattery2: boolean;
    battery2: Battery;
    controller: IsConnected & CommonController;
    offgridInverter: Inverter;
    hybridInverter: InverterHybrid;
    solarRadiation1: InputArrayType;
    solarRadiation2: InputArrayType;
    temperature: InputArrayType;
    windSpeed: InputArrayType;
    windDensity: InputType;
    alternCurrentLoadPower: InputArrayType;
    alternCurrentLoadPowerFactor: InputArrayType;
    directCurrentLoadPower: InputArrayType;
    directCurrentLoadConnected: boolean;
    solarRadiation1Array: number[];
    solarRadiation2Array: number[];
    temperatureArray: number[];
    windSpeedArray: number[];
    alternCurrentLoadPowerArray: number[];
    alternCurrentLoadPowerFactorArray: number[];
    directCurrentLoadPowerArray: number[];
    externalGridState: boolean;
    simulatedBatteryStateOfCharge?: number;
    simulatedDirectCurrentVoltage?: number;
    simulatedInverterState?: boolean;
    simulatedChargeCycle?: number;
    simulatedChargeCycleInitialSOC?: number;
  };

const MONOCRYSTALLINE_PANEL: SolarPanel = {
  isConnected: true,
  isConnectedDisabled: false,
  peakPower: {
    disabled: true,
    value: 100,
    tooltip: 'Potencia pico del generador solar',
    unit: 'W',
    variableString: 'Potencia pico',
  },
  ...MP,
};

const POLICRYSTALLINE_PANEL: SolarPanel = {
  isConnected: false,
  isConnectedDisabled: false,
  peakPower: {
    disabled: true,
    value: 100,
    tooltip: 'Potencia pico del generador solar',
    unit: 'W',
    variableString: 'Potencia pico',
  },
  ...PP,
};

const FLEX_PANEL: SolarPanel = {
  isConnected: false,
  isConnectedDisabled: false,
  peakPower: {
    disabled: true,
    value: 100,
    tooltip: 'Potencia pico del generador solar',
    unit: 'W',
    variableString: 'Potencia pico',
  },
  ...FP,
};

const CADMIUM_TELLURIDE_PANEL: SolarPanel = {
  isConnected: false,
  isConnectedDisabled: false,
  peakPower: {
    disabled: true,
    value: 77.5,
    tooltip: 'Potencia pico del generador solar',
    unit: 'W',
    variableString: 'Potencia pico',
  },
  ...CTP,
};

const BATTERY: Battery = {
  stateOfCharge: {
    disabled: false,
    value: 50,
    tooltip: 'Estado de carga inicial',
    unit: '%',
    variableString: 'SOC',
    variableSubString: 'inicial',
    min: 0,
    max: 100,
  },
  temperatureCoefficient: {
    disabled: true,
    value: 0.6,
    tooltip: 'Coeficiente de temperatura',
    unit: '% / °C',
    variableString: 'δ',
    variableSubString: 'C',
  },
  capacity: {
    disabled: true,
    value: 110,
    tooltip: 'Capacidad',
    unit: 'Ah',
    variableString: 'Capacidad',
    variableSubString: 'bat',
  },
  selfDischargeCoefficient: {
    disabled: true,
    value: 2.5,
    tooltip: 'Coeficiente de autodescarga',
    unit: '% / mes',
    variableString: 'σ',
    variableSubString: 'bat',
  },
  chargeDischargeEfficiency: {
    disabled: true,
    value: 98,
    tooltip: 'Eficiencia de carga y descarga',
    unit: '%',
    variableString: 'η',
    variableSubString: 'bat',
  },
  temperatureCompensationCoefficient: {
    disabled: true,
    value: -0.015,
    tooltip: 'Coeficiente de compensación de temperatura',
    unit: 'V / °C',
    variableString: 'δ',
    variableSubString: 'V',
  },
};

const CONTROLLER: IsConnected & CommonController = {
  isConnected: true,
  isConnectedDisabled: false,
  customize: false,
  efficiency: {
    disabled: true,
    value: 96,
    tooltip: 'Eficiencia del controlador de carga',
    unit: '%',
    variableString: 'η',
    variableSubString: 'controller',
  },
  chargeVoltageBulk: {
    disabled: true,
    value: 13.6,
    tooltip: 'Voltaje de carga bulk',
    unit: 'V',
    variableString: 'V',
    variableSubString: 'bulk',
    min: 10,
    max: 35,
    step: 0.1,
  },
  chargeVoltageFloat: {
    disabled: true,
    value: 13.9,
    tooltip: 'Voltaje de carga flotante',
    unit: 'V',
    variableString: 'V',
    variableSubString: 'float',
    min: 10,
    max: 35,
    step: 0.1,
  },
  chargingMinimumVoltage: {
    disabled: true,
    value: 11,
    tooltip: 'Voltaje mínimo de inicio de carga',
    unit: 'V',
    variableString: 'V',
    variableSubString: 'bat_min',
    min: 10,
    max: 35,
    step: 0.1,
  },
};

const OFFGRID_INVERTER: Inverter = {
  isConnected: true,
  isConnectedDisabled: false,
  efficiency: {
    disabled: true,
    value: 90,
    tooltip: 'Eficiencia inversor',
    unit: '%',
    variableString: 'η',
    variableSubString: 'Inversor',
  },
  nominalPower: {
    disabled: true,
    value: 1500,
    tooltip: 'Potencia nominal inversor',
    unit: 'W',
    variableString: 'P',
    variableSubString: 'Inversor',
  },
  minimumVoltage: {
    disabled: true,
    value: 22,
    tooltip: 'Voltaje mínimo de operación',
    unit: 'V',
    variableString: 'V',
    variableSubString: 'min',
  },
};

const HYBRID_INVERTER: InverterHybrid = {
  isConnected: false,
  customize: false,
  isConnectedDisabled: false,
  efficiency: {
    disabled: true,
    value: 96,
    tooltip: 'Eficiencia inversor',
    unit: '%',
    variableString: 'η',
    variableSubString: 'Inversor',
  },
  nominalPower: {
    disabled: true,
    value: 1000,
    tooltip: 'Potencia nominal inversor',
    unit: 'W',
    variableString: 'P',
    variableSubString: 'Inversor',
  },
  chargeVoltageBulk: {
    disabled: true,
    value: 27.2,
    tooltip: 'Voltaje de carga bulk',
    unit: 'V',
    variableString: 'V',
    variableSubString: 'bulk',
    min: 20,
    max: 35,
    step: 0.1,
  },
  chargeVoltageFloat: {
    disabled: true,
    value: 27.8,
    tooltip: 'Voltaje de carga flotante',
    unit: 'V',
    variableString: 'V',
    variableSubString: 'float',
    min: 20,
    max: 35,
    step: 0.1,
  },
  chargingMinimumVoltage: {
    disabled: true,
    value: 22,
    tooltip: 'Voltaje mínimo de inicio de carga',
    unit: 'V',
    variableString: 'V',
    variableSubString: 'bat_min',
    min: 22,
    max: 35,
    step: 0.1,
  },
  minimumVoltage: {
    disabled: true,
    value: 22,
    tooltip: 'Voltaje mínimo de operación',
    unit: 'V',
    variableString: 'V',
    variableSubString: 'min',
  },
};

export type SolarWindOutput = {
  monocrystallinePanelTemperature: number;
  policrystallinePanelTemperature: number;
  flexPanelTemperature: number;
  cadmiumTelluridePanelTemperature: number;
  batteryCurrent: number;
  batteryPower: number;
  batteryStateOfCharge: number;
  batteryTemperature: number;
  batteryVoltage: number;
  batteryState: number;
  chargeCycle: number;
  controllerPower: number;
  controllerCurrent: number;
  directCurrentLoadVoltage: number;
  directCurrentVoltage: number;
  directCurrentLoadCurrent: number;
  directCurrentLoadPower: number;
  externalGridVoltage: number;
  externalGridPower: number;
  externalGridState: number;
  externalGridCurrent: number;
  hybridInverterActivePower: number;
  hybridInverterApparentPower: number;
  hybridInverterOutputCurrent: number;
  hybridInverterReactivePower: number;
  hybridInverterVoltage: number;
  inverterActivePower: number;
  inverterApparentPower: number;
  inverterOutputCurrent: number;
  inverterReactivePower: number;
  inverterVoltage: number;
  inverterInputPower: number;
  inverterState: boolean;
  inverterInputCurrent: number;
  solarPanelCurrent: number;
  solarPanelGeneratedEnergy: number;
  solarPanelPower: number;
  solarPanelTemperature: number;
  solarPanelVoltage: number;
  windTurbineCurrent: number;
  windTurbineGeneratedEnergy: number;
  windTurbinePower: number;
  windTurbineRevolutions: number;
  windTurbineVoltage: number;
  inputSolarRadiation1?: number;
  inputSolarRadiation2?: number;
  inputWindSpeed?: number;
  inputAlternCurrentLoadPower?: number;
  inputAlternCurrentLoadPowerFactor?: number;
  inputDirectCurrentLoadPower?: number;
  chargeCycleInitialSOC?: number;
  inverterEfficiency?: number;
};

export type SolarWindOutputHistoric = CommonChartType & {
  monocrystallinePanelTemperature: number[];
  policrystallinePanelTemperature: number[];
  flexPanelTemperature: number[];
  cadmiumTelluridePanelTemperature: number[];
  batteryCurrent: number[];
  batteryPower: number[];
  batteryStateOfCharge: number[];
  batteryTemperature: number[];
  batteryVoltage: number[];
  batteryState: number[];
  chargeCycle: number[];
  controllerPower: number[];
  controllerCurrent: number[];
  directCurrentLoadVoltage: number[];
  directCurrentVoltage: number[];
  directCurrentLoadPower: number[];
  directCurrentLoadCurrent: number[];
  externalGridVoltage: number[];
  externalGridPower: number[];
  externalGridState: number[];
  externalGridCurrent: number[];
  hybridInverterActivePower: number[];
  hybridInverterApparentPower: number[];
  hybridInverterOutputCurrent: number[];
  hybridInverterReactivePower: number[];
  hybridInverterVoltage: number[];
  inverterActivePower: number[];
  inverterApparentPower: number[];
  inverterOutputCurrent: number[];
  inverterReactivePower: number[];
  inverterVoltage: number[];
  inverterInputPower: number[];
  inverterState: boolean[];
  inverterInputCurrent: number[];
  solarPanelCurrent: number[];
  solarPanelGeneratedEnergy: number[];
  solarPanelPower: number[];
  solarPanelTemperature: number[];
  solarPanelVoltage: number[];
  windTurbineCurrent: number[];
  windTurbineGeneratedEnergy: number[];
  windTurbinePower: number[];
  windTurbineRevolutions: number[];
  windTurbineVoltage: number[];
};

export const SOLAR_WIND: SolarWindParameters = {
  name: 'Nombre',
  trainingMode: false,
  iteration: 1,
  inputProfileEnable: false,
  lampsHeight: 36,
  panelsAngle: {
    disabled: false,
    value: 0,
    tooltip: 'Ángulo de los páneles',
    unit: '°',
    variableString: '°',
    min: 0,
    max: 30,
    step: 5,
  },
  steps: {
    disabled: false,
    value: 1,
    tooltip: 'Número de pasos a simular',
    unit: '',
    variableString: 'Número de pasos',
    min: 1,
    max: 10000,
  },
  stepTime: {
    disabled: false,
    value: 1,
    tooltip: 'Tiempo por paso',
    unit: '',
    variableString: 'Tiempo por paso',
    min: 1,
    max: 10000,
    step: 1,
  },
  stepUnit: StepUnitType.Second,
  isBatteryConnected: true,
  queryTime: Constants.QUERY_TIME_OFFLINE,
  disableParameters: false,
  timeMultiplier: {
    disabled: false,
    value: 1,
    tooltip: 'Multiplicador de tiempo',
    unit: '',
    variableString: 'TM',
    min: 1,
    max: 60,
  },
  inputOfflineOperation: true,
  inputOperationMode: OperationModeType.Mode1,
  monocrystallinePanel: MONOCRYSTALLINE_PANEL,
  policrystallinePanel: POLICRYSTALLINE_PANEL,
  flexPanel: FLEX_PANEL,
  cadmiumTelluridePanel: CADMIUM_TELLURIDE_PANEL,
  windTurbine: WIND_TURBINE,
  battery1: BATTERY,
  isBattery2: false,
  battery2: BATTERY,
  controller: CONTROLLER,
  offgridInverter: OFFGRID_INVERTER,
  hybridInverter: HYBRID_INVERTER,
  solarRadiation1: {
    disabled: false,
    value: 800,
    tooltip: 'Irradiancia estructura 2',
    unit: 'W / m²',
    variableString: 'Irradiancia estructura 2',
    min: 0,
    max: 2000,
    step: 100,
    arrayEnabled: false,
  },
  solarRadiation2: {
    disabled: false,
    value: 800,
    tooltip: 'Irradiancia estructura 1',
    unit: 'W / m²',
    variableString: 'Irradiancia estructura 1',
    min: 0,
    max: 2000,
    step: 100,
    arrayEnabled: false,
  },
  temperature: {
    disabled: false,
    value: 32,
    tooltip: 'Temperatura ambiente panel',
    unit: '°C',
    variableString: 'Temperatura ambiente panel',
    min: -20,
    max: 60,
    arrayEnabled: false,
  },
  windSpeed: {
    disabled: false,
    value: 10,
    tooltip: 'Velocidad del viento',
    unit: 'm / s',
    variableString: 'Velocidad del viento',
    min: 0,
    max: 100,
    arrayEnabled: false,
  },
  windDensity: {
    disabled: false,
    value: 1.12,
    tooltip: 'Densidad del aire',
    unit: 'kg / m³',
    variableString: 'Densidad del aire',
    min: 0.8,
    max: 1.5,
    step: 0.01,
  },
  alternCurrentLoadPower: {
    disabled: false,
    value: 200,
    tooltip: 'Potencia de la carga de alterna',
    unit: 'W',
    variableString: 'Potencia',
    min: 0,
    max: 2000,
    step: 10,
    arrayEnabled: false,
  },
  alternCurrentLoadPowerFactor: {
    disabled: false,
    value: 1,
    tooltip: 'Factor de potencia de la carga de alterna',
    unit: '',
    variableString: 'Factor de potencia',
    min: -1,
    max: 1,
    step: 0.1,
    arrayEnabled: false,
  },
  directCurrentLoadPower: {
    disabled: false,
    value: 6,
    tooltip:
      'Potencia de la carga de directa. Limitado a 6 W en el equipo del laboratorio',
    unit: 'W',
    variableString: 'Potencia',
    min: 0,
    max: 2000,
    step: 10,
    arrayEnabled: false,
  },
  directCurrentLoadConnected: false,
  externalGridState: false,
  solarRadiation1Array: [],
  solarRadiation2Array: [],
  temperatureArray: [],
  windSpeedArray: [],
  alternCurrentLoadPowerArray: [],
  alternCurrentLoadPowerFactorArray: [],
  directCurrentLoadPowerArray: [],
};

const COMMON_VARIABLES: DiagramVariableType[] = [
  {
    name: 'Radiación solar 2',
    variable: 'inputSolarRadiation1',
    unit: 'W / m²',
    isShown: false,
  },
  {
    name: 'Radiación solar 1',
    variable: 'inputSolarRadiation2',
    unit: 'W / m²',
    isShown: false,
  },
  {
    name: 'Temperatura',
    variable: 'inputTemperature',
    unit: '°C',
    isShown: false,
  },
  {
    name: 'Velocidad del viento',
    variable: 'inputWindSpeed',
    unit: 'm / s',
    isShown: false,
  },
  {
    name: 'Potencia carga CD',
    variable: 'inputDirectCurrentLoadPower',
    unit: 'W',
    isShown: false,
  },
  {
    name: 'Potencia carga CA',
    variable: 'inputAlternCurrentLoadPower',
    unit: 'W',
    isShown: false,
  },
  {
    name: 'Factor de potencia carga CA',
    variable: 'inputAlternCurrentLoadPowerFactor',
    unit: '',
    isShown: false,
  },
];

export const MODE_1_CADMIO_MODE_2: DiagramVariableType[] = [
  ...COMMON_VARIABLES,
  {
    name: 'Potencia carga CA',
    variable: 'inputAlternCurrentLoadPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 0,
    x: 3500,
    y: 1680,
  },
  {
    name: 'Factor de potencia carga CA',
    variable: 'inputAlternCurrentLoadPowerFactor',
    unit: '',
    isShown: true,
    diagramName: 'FP',
    fixed: 2,
    x: 3500,
    y: 1760,
  },
  {
    name: 'Estado de carga baterías',
    variable: 'batteryStateOfCharge',
    unit: '%',
    isShown: true,
    diagramName: 'SOC',
    fixed: 3,
    x: 1650,
    y: 420,
  },
  {
    name: 'Potencia batería',
    variable: 'batteryPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1650,
    y: 340,
  },
  {
    name: 'Voltaje baterías',
    variable: 'batteryVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 3,
    x: 1650,
    y: 180,
  },
  {
    name: 'Corriente baterías',
    variable: 'batteryCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1650,
    y: 260,
  },
  {
    name: 'Estado batería',
    variable: 'batteryState',
    x: 1650,
    y: 500,
    diagramName: 'Estado',
    unit: '',
    fixed: 0,
    isShown: true,
  },
  {
    name: 'Temperatura panel monocristalino',
    variable: 'monocrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. mono',
    fixed: 1,
    x: 1280,
    y: 2060,
    hasAdditionalCondition: 1,
  },
  {
    name: 'Temperatura panel policristalino',
    variable: 'policrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. poli',
    fixed: 1,
    x: 1280,
    y: 2140,
    hasAdditionalCondition: 2,
  },
  {
    name: 'Temperatura panel película delgada',
    variable: 'flexPanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. película',
    fixed: 1,
    x: 1280,
    y: 2220,
    hasAdditionalCondition: 3,
  },
  {
    name: 'Temperatura panel Telururo de Cadmio',
    variable: 'cadmiumTelluridePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. Cadmio',
    fixed: 1,
    x: 1280,
    y: 2300,
    hasAdditionalCondition: 4,
  },
  {
    name: 'Potencia controlador',
    variable: 'controllerPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2260,
    y: 1610,
  },
  {
    name: 'Voltaje corriente directa',
    variable: 'directCurrentVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 2260,
    y: 1450,
  },
  {
    name: 'Corriente controlador',
    variable: 'controllerCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2260,
    y: 1530,
  },
  {
    name: 'Eficiencia controlador',
    variable: 'controllerEfficiency',
    unit: '%',
    isShown: true,
    diagramName: 'Eficiencia',
    fixed: 1,
    x: 2260,
    y: 1690,
  },
  {
    name: 'Potencia carga CD',
    variable: 'directCurrentLoadPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2220,
    y: 2040,
  },
  {
    name: 'Voltaje carga CD',
    variable: 'directCurrentLoadVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 2220,
    y: 1880,
  },
  {
    name: 'Corriente carga CD',
    variable: 'directCurrentLoadCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2220,
    y: 1960,
  },
  {
    name: 'Potencia aparente inversor',
    variable: 'inverterApparentPower',
    unit: 'VA',
    isShown: true,
    diagramName: 'P. aparente',
    fixed: 1,
    x: 3500,
    y: 1260,
  },
  {
    name: 'Potencia activa inversor',
    variable: 'inverterActivePower',
    unit: 'W',
    isShown: true,
    diagramName: 'P. activa',
    fixed: 1,
    x: 3500,
    y: 1180,
  },
  {
    name: 'Potencia reactiva inversor',
    variable: 'inverterReactivePower',
    unit: 'VAr',
    isShown: true,
    diagramName: 'P. reactiva',
    fixed: 1,
    x: 3500,
    y: 1340,
  },
  {
    name: 'Voltaje inversor',
    variable: 'inverterVoltage',
    unit: 'VAC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 3500,
    y: 1020,
  },
  {
    name: 'Corriente inversor',
    variable: 'inverterOutputCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 3500,
    y: 1100,
  },
  {
    name: 'Potencia entrada inversor',
    variable: 'inverterInputPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia In',
    fixed: 1,
    x: 3500,
    y: 620,
  },
  {
    name: 'Corriente entrada inversor',
    variable: 'inverterInputCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente In',
    fixed: 1,
    x: 3500,
    y: 540,
  },
  {
    name: 'Estado inversor',
    variable: 'inverterState',
    unit: '',
    isShown: true,
    diagramName: 'Estado',
    fixed: 0,
    x: 3500,
    y: 780,
  },
  {
    name: 'Eficiencia inversor',
    variable: 'inverterEfficiency',
    unit: '%',
    isShown: true,
    diagramName: 'Eficiencia',
    fixed: 1,
    x: 3500,
    y: 700,
  },
  {
    name: 'Potencia paneles solares',
    variable: 'solarPanelPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 460,
    y: 2240,
  },
  {
    name: 'Voltaje paneles solares',
    variable: 'solarPanelVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 460,
    y: 2080,
  },
  {
    name: 'Corriente paneles solares',
    variable: 'solarPanelCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 460,
    y: 2160,
  },
];

export const MODE_1_MODE_3: DiagramVariableType[] = [
  ...COMMON_VARIABLES,
  {
    name: 'Estado de carga baterías',
    variable: 'batteryStateOfCharge',
    unit: '%',
    isShown: true,
    diagramName: 'SOC',
    fixed: 3,
    x: 1650,
    y: 420,
  },
  {
    name: 'Potencia batería',
    variable: 'batteryPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1650,
    y: 340,
  },
  {
    name: 'Voltaje baterías',
    variable: 'batteryVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 3,
    x: 1650,
    y: 180,
  },
  {
    name: 'Corriente baterías',
    variable: 'batteryCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1650,
    y: 260,
  },
  {
    name: 'Estado batería',
    variable: 'batteryState',
    x: 1650,
    y: 500,
    diagramName: 'Estado',
    unit: '',
    fixed: 0,
    isShown: true,
  },
  {
    name: 'Temperatura panel monocristalino',
    variable: 'monocrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. mono',
    fixed: 1,
    x: 1280,
    y: 2060,
    hasAdditionalCondition: 1,
  },
  {
    name: 'Temperatura panel policristalino',
    variable: 'policrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. poli',
    fixed: 1,
    x: 1280,
    y: 2140,
    hasAdditionalCondition: 2,
  },
  {
    name: 'Temperatura panel película delgada',
    variable: 'flexPanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. película',
    fixed: 1,
    x: 1280,
    y: 2220,
    hasAdditionalCondition: 3,
  },
  {
    name: 'Temperatura panel Telururo de Cadmio',
    variable: 'cadmiumTelluridePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. Cadmio',
    fixed: 1,
    x: 1280,
    y: 2300,
    hasAdditionalCondition: 4,
  },
  {
    name: 'Potencia controlador',
    variable: 'controllerPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2260,
    y: 1610,
  },
  {
    name: 'Voltaje corriente directa',
    variable: 'directCurrentVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 2260,
    y: 1450,
  },
  {
    name: 'Corriente controlador',
    variable: 'controllerCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2260,
    y: 1530,
  },
  {
    name: 'Eficiencia controlador',
    variable: 'controllerEfficiency',
    unit: '%',
    isShown: true,
    diagramName: 'Eficiencia',
    fixed: 1,
    x: 2260,
    y: 1690,
  },
  {
    name: 'Potencia carga CD',
    variable: 'directCurrentLoadPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2220,
    y: 2040,
  },
  {
    name: 'Voltaje carga CD',
    variable: 'directCurrentLoadVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 2220,
    y: 1880,
  },
  {
    name: 'Corriente carga CD',
    variable: 'directCurrentLoadCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2220,
    y: 1960,
  },
  {
    name: 'Potencia paneles solares',
    variable: 'solarPanelPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 460,
    y: 2240,
  },
  {
    name: 'Voltaje paneles solares',
    variable: 'solarPanelVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 460,
    y: 2080,
  },
  {
    name: 'Corriente paneles solares',
    variable: 'solarPanelCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 460,
    y: 2160,
  },
];

export const MODE_2_HYBRID: DiagramVariableType[] = [
  ...COMMON_VARIABLES,
  {
    name: 'Potencia carga CA',
    variable: 'inputAlternCurrentLoadPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 0,
    x: 3050,
    y: 1300,
  },
  {
    name: 'Factor de potencia carga CA',
    variable: 'inputAlternCurrentLoadPowerFactor',
    unit: '',
    isShown: true,
    diagramName: 'FP',
    fixed: 2,
    x: 3050,
    y: 1380,
  },
  {
    name: 'Estado de carga baterías',
    variable: 'batteryStateOfCharge',
    unit: '%',
    isShown: true,
    diagramName: 'SOC',
    fixed: 3,
    x: 3050,
    y: 2060,
  },
  {
    name: 'Potencia batería',
    variable: 'batteryPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 3050,
    y: 1980,
  },
  {
    name: 'Voltaje baterías',
    variable: 'batteryVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 3,
    x: 3050,
    y: 1820,
  },
  {
    name: 'Corriente baterías',
    variable: 'batteryCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 3050,
    y: 1900,
  },
  {
    name: 'Estado batería',
    variable: 'batteryState',
    x: 3050,
    y: 2140,
    diagramName: 'Estado',
    unit: '',
    fixed: 0,
    isShown: true,
  },
  {
    name: 'Temperatura panel monocristalino',
    variable: 'monocrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. mono',
    fixed: 1,
    x: 900,
    y: 1100,
    hasAdditionalCondition: 1,
  },
  {
    name: 'Temperatura panel policristalino',
    variable: 'policrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. poli',
    fixed: 1,
    x: 900,
    y: 1180,
    hasAdditionalCondition: 2,
  },
  {
    name: 'Temperatura panel película delgada',
    variable: 'flexPanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. película',
    fixed: 1,
    x: 900,
    y: 1260,
    hasAdditionalCondition: 3,
  },
  {
    name: 'Temperatura panel Telururo de Cadmio',
    variable: 'cadmiumTelluridePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. Cadmio',
    fixed: 1,
    x: 900,
    y: 1340,
    hasAdditionalCondition: 4,
  },
  {
    name: 'Potencia red externa',
    variable: 'externalGridPower',
    unit: 'VA',
    isShown: true,
    diagramName: 'P. aparente',
    fixed: 1,
    x: 200,
    y: 1960,
  },
  {
    name: 'Voltaje red externa',
    variable: 'externalGridVoltage',
    unit: 'VAC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 200,
    y: 1800,
  },
  {
    name: 'Corriente red externa',
    variable: 'externalGridCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 200,
    y: 1880,
  },
  {
    name: 'Estado red externa',
    variable: 'externalGridState',
    unit: '',
    isShown: true,
    diagramName: 'Estado',
    fixed: 0,
    x: 200,
    y: 2040,
  },
  {
    name: 'Potencia aparente inversor híbrido',
    variable: 'hybridInverterApparentPower',
    unit: 'VA',
    isShown: true,
    diagramName: 'P. aparente',
    fixed: 1,
    x: 3050,
    y: 760,
  },
  {
    name: 'Potencia activa inversor híbrido',
    variable: 'hybridInverterActivePower',
    unit: 'W',
    isShown: true,
    diagramName: 'P. activa',
    fixed: 1,
    x: 3050,
    y: 680,
  },
  {
    name: 'Potencia reactiva inversor híbrido',
    variable: 'hybridInverterReactivePower',
    unit: 'VAr',
    isShown: true,
    diagramName: 'P. reactiva',
    fixed: 1,
    x: 3050,
    y: 840,
  },
  {
    name: 'Voltaje inversor híbrido',
    variable: 'hybridInverterVoltage',
    unit: 'VAC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 3050,
    y: 520,
  },
  {
    name: 'Corriente inversor híbrido',
    variable: 'hybridInverterOutputCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 3050,
    y: 600,
  },
  {
    name: 'Potencia paneles solares',
    variable: 'solarPanelPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 200,
    y: 1180,
  },
  {
    name: 'Voltaje paneles solares',
    variable: 'solarPanelVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 200,
    y: 1020,
  },
  {
    name: 'Corriente paneles solares',
    variable: 'solarPanelCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 200,
    y: 1100,
  },
  {
    name: 'Voltaje corriente directa paneles solares',
    variable: 'directCurrentVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 1700,
    y: 1600,
  },
  {
    name: 'Eficiencia inversor híbrido',
    variable: 'hybridEfficiency',
    unit: '%',
    isShown: true,
    diagramName: 'Eficiencia',
    fixed: 1,
    x: 1700,
    y: 1680,
  },
];

export const MODE_4: DiagramVariableType[] = [
  ...COMMON_VARIABLES,
  {
    name: 'Estado de carga baterías',
    variable: 'batteryStateOfCharge',
    unit: '%',
    isShown: true,
    diagramName: 'SOC',
    fixed: 3,
    x: 1650,
    y: 420,
  },
  {
    name: 'Potencia batería',
    variable: 'batteryPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1650,
    y: 340,
  },
  {
    name: 'Voltaje baterías',
    variable: 'batteryVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 3,
    x: 1650,
    y: 180,
  },
  {
    name: 'Corriente baterías',
    variable: 'batteryCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1650,
    y: 260,
  },
  {
    name: 'Estado batería',
    variable: 'batteryState',
    x: 1650,
    y: 500,
    diagramName: 'Estado',
    unit: '',
    fixed: 0,
    isShown: true,
  },
  {
    name: 'Potencia controlador',
    variable: 'controllerPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2260,
    y: 1610,
  },
  {
    name: 'Voltaje corriente directa',
    variable: 'directCurrentVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 2260,
    y: 1450,
  },
  {
    name: 'Corriente controlador',
    variable: 'controllerCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2260,
    y: 1530,
  },
  {
    name: 'Eficiencia controlador',
    variable: 'controllerEfficiency',
    unit: '%',
    isShown: true,
    diagramName: 'Eficiencia',
    fixed: 1,
    x: 2260,
    y: 1690,
  },
  {
    name: 'Potencia carga CD',
    variable: 'directCurrentLoadPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2220,
    y: 2040,
  },
  {
    name: 'Voltaje carga CD',
    variable: 'directCurrentLoadVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 2220,
    y: 1880,
  },
  {
    name: 'Corriente carga CD',
    variable: 'directCurrentLoadCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2220,
    y: 1960,
  },
  {
    name: 'Potencia turbina',
    variable: 'windTurbinePower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1120,
    y: 1200,
  },
  {
    name: 'Voltaje turbina',
    variable: 'windTurbineVoltage',
    unit: 'VAC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 1120,
    y: 1040,
  },
  {
    name: 'Corriente turbina',
    variable: 'windTurbineCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1120,
    y: 1120,
  },
  {
    name: 'Revoluciones turbina',
    variable: 'windTurbineRevolutions',
    unit: 'rpm',
    isShown: true,
    diagramName: 'Revoluciones',
    fixed: 0,
    x: 1120,
    y: 1280,
    hasAdditionalCondition: 0,
  },
];

export const MODE_4_INVERTER: DiagramVariableType[] = [
  ...COMMON_VARIABLES,
  {
    name: 'Estado de carga baterías',
    variable: 'batteryStateOfCharge',
    unit: '%',
    isShown: true,
    diagramName: 'SOC',
    fixed: 3,
    x: 1650,
    y: 420,
  },
  {
    name: 'Potencia batería',
    variable: 'batteryPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1650,
    y: 340,
  },
  {
    name: 'Voltaje baterías',
    variable: 'batteryVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 3,
    x: 1650,
    y: 180,
  },
  {
    name: 'Corriente baterías',
    variable: 'batteryCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1650,
    y: 260,
  },
  {
    name: 'Estado batería',
    variable: 'batteryState',
    x: 1650,
    y: 500,
    diagramName: 'Estado',
    unit: '',
    fixed: 0,
    isShown: true,
  },
  {
    name: 'Potencia controlador',
    variable: 'controllerPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2260,
    y: 1610,
  },
  {
    name: 'Voltaje corriente directa',
    variable: 'directCurrentVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 2260,
    y: 1450,
  },
  {
    name: 'Corriente controlador',
    variable: 'controllerCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2260,
    y: 1530,
  },
  {
    name: 'Eficiencia controlador',
    variable: 'controllerEfficiency',
    unit: '%',
    isShown: true,
    diagramName: 'Eficiencia',
    fixed: 1,
    x: 2260,
    y: 1690,
  },
  {
    name: 'Potencia carga CD',
    variable: 'directCurrentLoadPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2220,
    y: 2040,
  },
  {
    name: 'Voltaje carga CD',
    variable: 'directCurrentLoadVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 2220,
    y: 1880,
  },
  {
    name: 'Corriente carga CD',
    variable: 'directCurrentLoadCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2220,
    y: 1960,
  },
  {
    name: 'Potencia turbina',
    variable: 'windTurbinePower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1120,
    y: 1200,
  },
  {
    name: 'Voltaje turbina',
    variable: 'windTurbineVoltage',
    unit: 'VAC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 1120,
    y: 1040,
  },
  {
    name: 'Corriente turbina',
    variable: 'windTurbineCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1120,
    y: 1120,
  },
  {
    name: 'Revoluciones turbina',
    variable: 'windTurbineRevolutions',
    unit: 'rpm',
    isShown: true,
    diagramName: 'Revoluciones',
    fixed: 0,
    x: 1120,
    y: 1280,
    hasAdditionalCondition: 0,
  },
  {
    name: 'Potencia carga CA',
    variable: 'inputAlternCurrentLoadPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 0,
    x: 3500,
    y: 1680,
  },
  {
    name: 'Factor de potencia carga CA',
    variable: 'inputAlternCurrentLoadPowerFactor',
    unit: '',
    isShown: true,
    diagramName: 'FP',
    fixed: 2,
    x: 3500,
    y: 1760,
  },
  {
    name: 'Potencia aparente inversor',
    variable: 'inverterApparentPower',
    unit: 'VA',
    isShown: true,
    diagramName: 'P. aparente',
    fixed: 1,
    x: 3500,
    y: 1260,
  },
  {
    name: 'Potencia activa inversor',
    variable: 'inverterActivePower',
    unit: 'W',
    isShown: true,
    diagramName: 'P. activa',
    fixed: 1,
    x: 3500,
    y: 1180,
  },
  {
    name: 'Potencia reactiva inversor',
    variable: 'inverterReactivePower',
    unit: 'VAr',
    isShown: true,
    diagramName: 'P. reactiva',
    fixed: 1,
    x: 3500,
    y: 1340,
  },
  {
    name: 'Voltaje inversor',
    variable: 'inverterVoltage',
    unit: 'VAC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 3500,
    y: 1020,
  },
  {
    name: 'Corriente inversor',
    variable: 'inverterOutputCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 3500,
    y: 1100,
  },
  {
    name: 'Potencia entrada inversor',
    variable: 'inverterInputPower',
    unit: 'W',
    isShown: true,
    diagramName: 'P. entrada',
    fixed: 1,
    x: 3500,
    y: 620,
  },
  {
    name: 'Corriente entrada inversor',
    variable: 'inverterInputCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'I. entrada',
    fixed: 1,
    x: 3500,
    y: 540,
  },
  {
    name: 'Estado inversor',
    variable: 'inverterState',
    unit: '',
    isShown: true,
    diagramName: 'Estado',
    fixed: 0,
    x: 3500,
    y: 780,
  },
  {
    name: 'Eficiencia inversor',
    variable: 'inverterEfficiency',
    unit: '%',
    isShown: true,
    diagramName: 'Eficiencia',
    fixed: 1,
    x: 3500,
    y: 700,
  },
];

export const MODE_5: DiagramVariableType[] = [
  ...COMMON_VARIABLES,
  {
    name: 'Estado de carga baterías',
    variable: 'batteryStateOfCharge',
    unit: '%',
    isShown: true,
    diagramName: 'SOC',
    fixed: 3,
    x: 1650,
    y: 420,
  },
  {
    name: 'Potencia batería',
    variable: 'batteryPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1650,
    y: 340,
  },
  {
    name: 'Voltaje baterías',
    variable: 'batteryVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 3,
    x: 1650,
    y: 180,
  },
  {
    name: 'Corriente baterías',
    variable: 'batteryCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1650,
    y: 260,
  },
  {
    name: 'Estado batería',
    variable: 'batteryState',
    x: 1650,
    y: 500,
    diagramName: 'Estado',
    unit: '',
    fixed: 0,
    isShown: true,
  },
  {
    name: 'Temperatura panel monocristalino',
    variable: 'monocrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. mono',
    fixed: 1,
    x: 1280,
    y: 2060,
    hasAdditionalCondition: 1,
  },
  {
    name: 'Temperatura panel policristalino',
    variable: 'policrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. poli',
    fixed: 1,
    x: 1280,
    y: 2140,
    hasAdditionalCondition: 2,
  },
  {
    name: 'Temperatura panel película delgada',
    variable: 'flexPanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. película',
    fixed: 1,
    x: 1280,
    y: 2220,
    hasAdditionalCondition: 3,
  },
  {
    name: 'Temperatura panel Telururo de Cadmio',
    variable: 'cadmiumTelluridePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. Cadmio',
    fixed: 1,
    x: 1280,
    y: 2300,
    hasAdditionalCondition: 4,
  },
  {
    name: 'Potencia controlador',
    variable: 'controllerPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2260,
    y: 1610,
  },
  {
    name: 'Voltaje corriente directa',
    variable: 'directCurrentVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 2260,
    y: 1450,
  },
  {
    name: 'Corriente controlador',
    variable: 'controllerCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2260,
    y: 1530,
  },
  {
    name: 'Eficiencia controlador',
    variable: 'controllerEfficiency',
    unit: '%',
    isShown: true,
    diagramName: 'Eficiencia',
    fixed: 1,
    x: 2260,
    y: 1690,
  },
  {
    name: 'Potencia carga CD',
    variable: 'directCurrentLoadPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2220,
    y: 2040,
  },
  {
    name: 'Voltaje carga CD',
    variable: 'directCurrentLoadVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 2220,
    y: 1880,
  },
  {
    name: 'Corriente carga CD',
    variable: 'directCurrentLoadCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2220,
    y: 1960,
  },
  {
    name: 'Potencia paneles solares',
    variable: 'solarPanelPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 460,
    y: 2240,
  },
  {
    name: 'Voltaje paneles solares',
    variable: 'solarPanelVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 460,
    y: 2080,
  },
  {
    name: 'Corriente paneles solares',
    variable: 'solarPanelCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 460,
    y: 2160,
  },
  {
    name: 'Potencia turbina',
    variable: 'windTurbinePower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1120,
    y: 1200,
  },
  {
    name: 'Voltaje turbina',
    variable: 'windTurbineVoltage',
    unit: 'VAC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 1120,
    y: 1040,
  },
  {
    name: 'Corriente turbina',
    variable: 'windTurbineCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1120,
    y: 1120,
  },
  {
    name: 'Revoluciones turbina',
    variable: 'windTurbineRevolutions',
    unit: 'rpm',
    isShown: true,
    diagramName: 'Revoluciones',
    fixed: 0,
    x: 1120,
    y: 1280,
    hasAdditionalCondition: 0,
  },
];

export const MODE_5_INVERTER: DiagramVariableType[] = [
  ...COMMON_VARIABLES,
  {
    name: 'Estado de carga baterías',
    variable: 'batteryStateOfCharge',
    unit: '%',
    isShown: true,
    diagramName: 'SOC',
    fixed: 3,
    x: 1650,
    y: 420,
  },
  {
    name: 'Potencia batería',
    variable: 'batteryPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1650,
    y: 340,
  },
  {
    name: 'Voltaje baterías',
    variable: 'batteryVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 3,
    x: 1650,
    y: 180,
  },
  {
    name: 'Corriente baterías',
    variable: 'batteryCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1650,
    y: 260,
  },
  {
    name: 'Estado batería',
    variable: 'batteryState',
    x: 1650,
    y: 500,
    diagramName: 'Estado',
    unit: '',
    fixed: 0,
    isShown: true,
  },
  {
    name: 'Temperatura panel monocristalino',
    variable: 'monocrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. mono',
    fixed: 1,
    x: 1280,
    y: 2060,
    hasAdditionalCondition: 1,
  },
  {
    name: 'Temperatura panel policristalino',
    variable: 'policrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. poli',
    fixed: 1,
    x: 1280,
    y: 2140,
    hasAdditionalCondition: 2,
  },
  {
    name: 'Temperatura panel película delgada',
    variable: 'flexPanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. película',
    fixed: 1,
    x: 1280,
    y: 2220,
    hasAdditionalCondition: 3,
  },
  {
    name: 'Temperatura panel Telururo de Cadmio',
    variable: 'cadmiumTelluridePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. Cadmio',
    fixed: 1,
    x: 1280,
    y: 2300,
    hasAdditionalCondition: 4,
  },
  {
    name: 'Potencia controlador',
    variable: 'controllerPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2260,
    y: 1610,
  },
  {
    name: 'Voltaje corriente directa',
    variable: 'directCurrentVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 2260,
    y: 1450,
  },
  {
    name: 'Corriente controlador',
    variable: 'controllerCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2260,
    y: 1530,
  },
  {
    name: 'Eficiencia controlador',
    variable: 'controllerEfficiency',
    unit: '%',
    isShown: true,
    diagramName: 'Eficiencia',
    fixed: 1,
    x: 2260,
    y: 1690,
  },
  {
    name: 'Potencia carga CD',
    variable: 'directCurrentLoadPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2220,
    y: 2040,
  },
  {
    name: 'Voltaje carga CD',
    variable: 'directCurrentLoadVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 2220,
    y: 1880,
  },
  {
    name: 'Corriente carga CD',
    variable: 'directCurrentLoadCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2220,
    y: 1960,
  },
  {
    name: 'Potencia paneles solares',
    variable: 'solarPanelPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 460,
    y: 2240,
  },
  {
    name: 'Voltaje paneles solares',
    variable: 'solarPanelVoltage',
    unit: 'VDC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 460,
    y: 2080,
  },
  {
    name: 'Corriente paneles solares',
    variable: 'solarPanelCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 460,
    y: 2160,
  },
  {
    name: 'Potencia turbina',
    variable: 'windTurbinePower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1120,
    y: 1200,
  },
  {
    name: 'Voltaje turbina',
    variable: 'windTurbineVoltage',
    unit: 'VAC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 1120,
    y: 1040,
  },
  {
    name: 'Corriente turbina',
    variable: 'windTurbineCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1120,
    y: 1120,
  },
  {
    name: 'Revoluciones turbina',
    variable: 'windTurbineRevolutions',
    unit: 'rpm',
    isShown: true,
    diagramName: 'Revoluciones',
    fixed: 0,
    x: 1120,
    y: 1280,
    hasAdditionalCondition: 0,
  },
  {
    name: 'Potencia carga CA',
    variable: 'inputAlternCurrentLoadPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 0,
    x: 3500,
    y: 1680,
  },
  {
    name: 'Factor de potencia carga CA',
    variable: 'inputAlternCurrentLoadPowerFactor',
    unit: '',
    isShown: true,
    diagramName: 'FP',
    fixed: 2,
    x: 3500,
    y: 1760,
  },
  {
    name: 'Potencia aparente inversor',
    variable: 'inverterApparentPower',
    unit: 'VA',
    isShown: true,
    diagramName: 'P. aparente',
    fixed: 1,
    x: 3500,
    y: 1260,
  },
  {
    name: 'Potencia activa inversor',
    variable: 'inverterActivePower',
    unit: 'W',
    isShown: true,
    diagramName: 'P. activa',
    fixed: 1,
    x: 3500,
    y: 1180,
  },
  {
    name: 'Potencia reactiva inversor',
    variable: 'inverterReactivePower',
    unit: 'VAr',
    isShown: true,
    diagramName: 'P. reactiva',
    fixed: 1,
    x: 3500,
    y: 1340,
  },
  {
    name: 'Voltaje inversor',
    variable: 'inverterVoltage',
    unit: 'VAC',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 3500,
    y: 1020,
  },
  {
    name: 'Corriente inversor',
    variable: 'inverterOutputCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 3500,
    y: 1100,
  },
  {
    name: 'Potencia entrada inversor',
    variable: 'inverterInputPower',
    unit: 'W',
    isShown: true,
    diagramName: 'P. entrada',
    fixed: 1,
    x: 3500,
    y: 620,
  },
  {
    name: 'Corriente entrada inversor',
    variable: 'inverterInputCurrent',
    unit: 'A',
    isShown: true,
    diagramName: 'I. entrada',
    fixed: 1,
    x: 3500,
    y: 540,
  },
  {
    name: 'Estado inversor',
    variable: 'inverterState',
    unit: '',
    isShown: true,
    diagramName: 'Estado',
    fixed: 0,
    x: 3500,
    y: 780,
  },
  {
    name: 'Eficiencia inversor',
    variable: 'inverterEfficiency',
    unit: '%',
    isShown: true,
    diagramName: 'Eficiencia',
    fixed: 1,
    x: 3500,
    y: 700,
  },
];
