import Config from '../../config/config';
import { CommonGraphType } from '../graph';
import {
  Battery,
  CommonController,
  CommonDigitalTwinsParameter,
  CommonSystemParameter,
  DiagramVariableType,
  InputType,
  Inverter,
  InverterHybrid,
  IsConnected,
  SolarPanel,
  WindTurbine,
} from './common';

export enum OperationModeType {
  Mode1 = 'Mode1',
  Mode2 = 'Mode2',
  Mode3 = 'Mode3',
  Mode4 = 'Mode4',
  Mode5 = 'Mode5',
}

export enum OperationModeText {
  Mode1 = 'Paneles individuales',
  Mode2 = 'Paneles en serie',
  Mode3 = 'Paneles en paralelo',
  Mode4 = 'Aerogenerador',
  Mode5 = 'Paneles y aerogenerador',
}

export type SolarWindParameters = CommonSystemParameter &
  CommonDigitalTwinsParameter & {
    inputOperationMode: OperationModeType;
    monocrystallinePanel: SolarPanel;
    policrystallinePanel: SolarPanel;
    flexPanel: SolarPanel;
    cadmiumTelluridePanel: SolarPanel;
    windTurbine: WindTurbine;
    battery1: Battery;
    isBattery2: boolean;
    battery2: Battery;
    controller: IsConnected & CommonController;
    offgridInverter: Inverter;
    hybridInverter: InverterHybrid;
    solarRadiation1: InputType;
    solarRadiation2: InputType;
    temperature: InputType;
    windSpeed: InputType;
    windDensity: InputType;
    alternCurrentLoadPower: InputType;
    alternCurrentLoadPowerFactor: InputType;
    directCurrentLoadPower: InputType;
    externalGridState: boolean;
    simulatedBatteryStateOfCharge?: number;
    simulatedDirectCurrentVoltage?: number;
    simulatedInverterState?: boolean;
    simulatedChargeCycle?: number;
  };

const MONOCRYSTALLINE_PANEL: SolarPanel = {
  isConnected: true,
  isConnectedDisabled: false,
  peakPower: {
    disabled: true,
    value: 100,
    tooltip: 'Potencia pico del generador solar',
    unit: 'W',
    variableString: 'Potencia pico',
  },
  deratingFactor: {
    disabled: false,
    value: 1,
    tooltip: 'Factor de reducción de la potencia',
    unit: '',
    variableString: 'f',
    variableSubString: 'pu',
    min: 0.7,
    max: 1,
    step: 0.01,
  },
  efficiency: {
    disabled: true,
    value: 15.44,
    tooltip: 'Eficiencia del panel',
    unit: '%',
    variableString: 'η',
    variableSubString: 'C',
  },
  nominalIrradiance: {
    disabled: true,
    value: 800,
    tooltip: 'Irradiancia a condiciones nominales de operación',
    unit: 'W / m²',
    variableString: 'G',
    variableSubString: 'NOCT',
  },
  testIrradiance: {
    disabled: true,
    value: 1000,
    tooltip: 'Irradiancia a condiciones estándar de prueba',
    unit: 'W / m²',
    variableString: 'G',
    variableSubString: 'STC',
  },
  nominalTemperature: {
    disabled: true,
    value: 45,
    tooltip: 'Temperatura del módulo en condiciones nominales de operación',
    unit: '°C',
    variableString: 'Tc',
    variableSubString: 'NOCT',
  },
  testTemperature: {
    disabled: true,
    value: 25,
    tooltip: 'Temperatura del módulo en condiciones estándar de prueba',
    unit: '°C',
    variableString: 'Tc',
    variableSubString: 'STC',
  },
  operatingTemperature: {
    disabled: true,
    value: 20,
    tooltip: 'Temperatura ambiente normal de operación',
    unit: '°C',
    variableString: 'Ta',
    variableSubString: 'NOCT',
  },
  temperatureVariationCoefficient: {
    disabled: true,
    value: -0.39,
    tooltip: 'Coeficiente de variación de la potencia con la temperatura',
    unit: '% / °C',
    variableString: 'μ',
    variableSubString: 'pm',
  },
};

const POLICRYSTALLINE_PANEL: SolarPanel = {
  isConnected: false,
  isConnectedDisabled: false,
  peakPower: {
    disabled: true,
    value: 100,
    tooltip: 'Potencia pico del generador solar',
    unit: 'W',
    variableString: 'Potencia pico',
  },
  deratingFactor: {
    disabled: false,
    value: 1,
    tooltip: 'Factor de reducción de la potencia',
    unit: '',
    variableString: 'f',
    variableSubString: 'pu',
    min: 0.7,
    max: 1,
    step: 0.01,
  },
  efficiency: {
    disabled: true,
    value: 15.44,
    tooltip: 'Eficiencia del panel',
    unit: '%',
    variableString: 'η',
    variableSubString: 'C',
  },
  nominalIrradiance: {
    disabled: true,
    value: 800,
    tooltip: 'Irradiancia a condiciones nominales de operación',
    unit: 'W / m²',
    variableString: 'G',
    variableSubString: 'NOCT',
  },
  testIrradiance: {
    disabled: true,
    value: 1000,
    tooltip: 'Irradiancia a condiciones estándar de prueba',
    unit: 'W / m²',
    variableString: 'G',
    variableSubString: 'STC',
  },
  nominalTemperature: {
    disabled: true,
    value: 45,
    tooltip: 'Temperatura del módulo en condiciones nominales de operación',
    unit: '°C',
    variableString: 'Tc',
    variableSubString: 'NOCT',
  },
  testTemperature: {
    disabled: true,
    value: 25,
    tooltip: 'Temperatura del módulo en condiciones estándar de prueba',
    unit: '°C',
    variableString: 'Tc',
    variableSubString: 'STC',
  },
  operatingTemperature: {
    disabled: true,
    value: 20,
    tooltip: 'Temperatura ambiente normal de operación',
    unit: '°C',
    variableString: 'Ta',
    variableSubString: 'NOCT',
  },
  temperatureVariationCoefficient: {
    disabled: true,
    value: -0.39,
    tooltip: 'Coeficiente de variación de la potencia con la temperatura',
    unit: '% / °C',
    variableString: 'μ',
    variableSubString: 'pm',
  },
};

const FLEX_PANEL: SolarPanel = {
  isConnected: false,
  isConnectedDisabled: false,
  peakPower: {
    disabled: true,
    value: 100,
    tooltip: 'Potencia pico del generador solar',
    unit: 'W',
    variableString: 'Potencia pico',
  },
  deratingFactor: {
    disabled: false,
    value: 1,
    tooltip: 'Factor de reducción de la potencia',
    unit: '',
    variableString: 'f',
    variableSubString: 'pu',
    min: 0.7,
    max: 1,
    step: 0.01,
  },
  efficiency: {
    disabled: true,
    value: 15.43,
    tooltip: 'Eficiencia del panel',
    unit: '%',
    variableString: 'η',
    variableSubString: 'C',
  },
  nominalIrradiance: {
    disabled: true,
    value: 800,
    tooltip: 'Irradiancia a condiciones nominales de operación',
    unit: 'W / m²',
    variableString: 'G',
    variableSubString: 'NOCT',
  },
  testIrradiance: {
    disabled: true,
    value: 1000,
    tooltip: 'Irradiancia a condiciones estándar de prueba',
    unit: 'W / m²',
    variableString: 'G',
    variableSubString: 'STC',
  },
  nominalTemperature: {
    disabled: true,
    value: 45,
    tooltip: 'Temperatura del módulo en condiciones nominales de operación',
    unit: '°C',
    variableString: 'Tc',
    variableSubString: 'NOCT',
  },
  testTemperature: {
    disabled: true,
    value: 25,
    tooltip: 'Temperatura del módulo en condiciones estándar de prueba',
    unit: '°C',
    variableString: 'Tc',
    variableSubString: 'STC',
  },
  operatingTemperature: {
    disabled: true,
    value: 20,
    tooltip: 'Temperatura ambiente normal de operación',
    unit: '°C',
    variableString: 'Ta',
    variableSubString: 'NOCT',
  },
  temperatureVariationCoefficient: {
    disabled: true,
    value: -0.42,
    tooltip: 'Coeficiente de variación de la potencia con la temperatura',
    unit: '% / °C',
    variableString: 'μ',
    variableSubString: 'pm',
  },
};

const CADMIUM_TELLURIDE_PANEL: SolarPanel = {
  isConnected: false,
  isConnectedDisabled: false,
  peakPower: {
    disabled: true,
    value: 77.5,
    tooltip: 'Potencia pico del generador solar',
    unit: 'W',
    variableString: 'Potencia pico',
  },
  deratingFactor: {
    disabled: false,
    value: 1,
    tooltip: 'Factor de reducción de la potencia',
    unit: '',
    variableString: 'f',
    variableSubString: 'pu',
    min: 0.7,
    max: 1,
    step: 0.01,
  },
  efficiency: {
    disabled: true,
    value: 11,
    tooltip: 'Eficiencia del panel',
    unit: '%',
    variableString: 'η',
    variableSubString: 'C',
  },
  nominalIrradiance: {
    disabled: true,
    value: 800,
    tooltip: 'Irradiancia a condiciones nominales de operación',
    unit: 'W / m²',
    variableString: 'G',
    variableSubString: 'NOCT',
  },
  testIrradiance: {
    disabled: true,
    value: 1000,
    tooltip: 'Irradiancia a condiciones estándar de prueba',
    unit: 'W / m²',
    variableString: 'G',
    variableSubString: 'STC',
  },
  nominalTemperature: {
    disabled: true,
    value: 42,
    tooltip: 'Temperatura del módulo en condiciones nominales de operación',
    unit: '°C',
    variableString: 'Tc',
    variableSubString: 'NOCT',
  },
  testTemperature: {
    disabled: true,
    value: 25,
    tooltip: 'Temperatura del módulo en condiciones estándar de prueba',
    unit: '°C',
    variableString: 'Tc',
    variableSubString: 'STC',
  },
  operatingTemperature: {
    disabled: true,
    value: 20,
    tooltip: 'Temperatura ambiente normal de operación',
    unit: '°C',
    variableString: 'Ta',
    variableSubString: 'NOCT',
  },
  temperatureVariationCoefficient: {
    disabled: true,
    value: -0.25,
    tooltip: 'Coeficiente de variación de la potencia con la temperatura',
    unit: '% / °C',
    variableString: 'μ',
    variableSubString: 'pm',
  },
};

const WIND_TURBINE: WindTurbine = {
  peakPower: {
    disabled: true,
    value: 200,
    tooltip: 'Potencia pico del aerogenerador',
    unit: 'W',
    variableString: 'Potencia pico',
  },
  rotorHeight: {
    disabled: false,
    value: 1.5,
    tooltip: 'Altura del rotor del aerogenerador',
    unit: 'm',
    variableString: 'H',
    variableSubString: 'r',
    min: 0,
    max: 10,
    step: 0.1,
  },
  anemometerHeight: {
    disabled: false,
    value: 1.5,
    tooltip: 'Altura del anemómetro',
    unit: 'm',
    variableString: 'H',
    variableSubString: 'a',
    min: 0,
    max: 10,
    step: 0.1,
  },
  ratedWindSpeed: {
    disabled: true,
    value: 11.5,
    tooltip: 'Velocidad de viento nominal',
    unit: 'm / s',
    variableString: 'V',
    variableSubString: 'n',
  },
  lowerCutoffWindSpeed: {
    disabled: true,
    value: 2,
    tooltip: 'Velocidad de viento de corte inferior',
    unit: 'm / s',
    variableString: 'V',
    variableSubString: 'f',
  },
  upperCutoffWindSpeed: {
    disabled: true,
    value: 65,
    tooltip: 'Velocidad de viento de corte superior',
    unit: 'm / s',
    variableString: 'V',
    variableSubString: 'c',
  },
};

const BATTERY: Battery = {
  stateOfCharge: {
    disabled: false,
    value: 50,
    tooltip: 'Estado de carga inicial',
    unit: '%',
    variableString: 'SOC',
    variableSubString: 'inicial',
    min: 0,
    max: 100,
  },
  temperatureCoefficient: {
    disabled: true,
    value: 0.6,
    tooltip: 'Coeficiente de temperatura',
    unit: '% / °C',
    variableString: 'δ',
    variableSubString: 'C',
  },
  capacity: {
    disabled: true,
    value: 50,
    tooltip: 'Capacidad',
    unit: 'Ah',
    variableString: 'Capacidad',
    variableSubString: 'bat',
  },
  selfDischargeCoefficient: {
    disabled: true,
    value: 0.08,
    tooltip: 'Coeficiente de autodescarga',
    unit: '% / dia',
    variableString: 'σ',
    variableSubString: 'bat',
  },
  chargeDischargeEfficiency: {
    disabled: true,
    value: 98,
    tooltip: 'Eficiencia de carga y descarga',
    unit: '% / mes',
    variableString: 'η',
    variableSubString: 'bat',
  },
  temperatureCompensationCoefficient: {
    disabled: true,
    value: -0.015,
    tooltip: 'Coeficiente de compensación de temperatura',
    unit: 'V / °C',
    variableString: 'δ',
    variableSubString: 'V',
  },
};

const CONTROLLER: IsConnected & CommonController = {
  isConnected: true,
  isConnectedDisabled: false,
  customize: false,
  efficiency: {
    disabled: true,
    value: 96,
    tooltip: 'Eficiencia del controlador de carga',
    unit: '%',
    variableString: 'η',
    variableSubString: 'controller',
  },
  chargeVoltageBulk: {
    disabled: true,
    value: 13.6,
    tooltip: 'Voltaje de carga bulk',
    unit: 'V',
    variableString: 'V',
    variableSubString: 'bulk',
    min: 10,
    max: 35,
    step: 0.1,
  },
  chargeVoltageFloat: {
    disabled: true,
    value: 13.9,
    tooltip: 'Voltaje de carga flotante',
    unit: 'V',
    variableString: 'V',
    variableSubString: 'float',
    min: 10,
    max: 35,
    step: 0.1,
  },
  chargingMinimunVoltage: {
    disabled: true,
    value: 11.5,
    tooltip: 'Voltaje mínimo de inicio de carga',
    unit: 'V',
    variableString: 'V',
    variableSubString: 'bat_min',
    min: 10,
    max: 35,
    step: 0.1,
  },
};

const OFFGRID_INVERTER: Inverter = {
  isConnected: true,
  isConnectedDisabled: false,
  efficiency: {
    disabled: true,
    value: 90,
    tooltip: 'Eficiencia inversor',
    unit: '%',
    variableString: 'η',
    variableSubString: 'Inversor',
  },
  nominalPower: {
    disabled: true,
    value: 1500,
    tooltip: 'Potencia nominal inversor',
    unit: 'W',
    variableString: 'P',
    variableSubString: 'Inversor',
  },
};

const HYBRID_INVERTER: InverterHybrid = {
  isConnected: false,
  customize: false,
  isConnectedDisabled: false,
  efficiency: {
    disabled: true,
    value: 90,
    tooltip: 'Eficiencia inversor',
    unit: '%',
    variableString: 'η',
    variableSubString: 'Inversor',
  },
  nominalPower: {
    disabled: true,
    value: 1000,
    tooltip: 'Potencia nominal inversor',
    unit: 'W',
    variableString: 'P',
    variableSubString: 'Inversor',
  },
  chargeVoltageBulk: {
    disabled: true,
    value: 27.2,
    tooltip: 'Voltaje de carga bulk',
    unit: 'V',
    variableString: 'V',
    variableSubString: 'bulk',
    min: 20,
    max: 35,
    step: 0.1,
  },
  chargeVoltageFloat: {
    disabled: true,
    value: 27.8,
    tooltip: 'Voltaje de carga flotante',
    unit: 'V',
    variableString: 'V',
    variableSubString: 'float',
    min: 20,
    max: 35,
    step: 0.1,
  },
  chargingMinimunVoltage: {
    disabled: true,
    value: 23,
    tooltip: 'Voltaje mínimo de inicio de carga',
    unit: 'V',
    variableString: 'V',
    variableSubString: 'bat_min',
    min: 22,
    max: 35,
    step: 0.1,
  },
};

export type SolarWindOutput = {
  monocrystallinePanelTemperature: number;
  policrystallinePanelTemperature: number;
  flexPanelTemperature: number;
  cadmiumTelluridePanelTemperature: number;
  batteryCurrent: number;
  batteryPower: number;
  batteryStateOfCharge: number;
  batteryTemperature: number;
  batteryVoltage: number;
  chargeCycle: number;
  controllerPower: number;
  controllerCurrent: number;
  directCurrentLoadVoltage: number;
  directCurrentVoltage: number;
  directCurrentLoadCurrent: number;
  externalGridVoltage: number;
  externalGridPower: number;
  externalGridState: number;
  externalGridCurrent: number;
  hybridInverterActivePower: number;
  hybridInverterApparentPower: number;
  hybridInverterOutputCurrent: number;
  hybridInverterReactivePower: number;
  hybridInverterVoltage: number;
  inverterActivePower: number;
  inverterApparentPower: number;
  inverterOutputCurrent: number;
  inverterReactivePower: number;
  inverterVoltage: number;
  inverterInputPower: number;
  inverterState: boolean;
  inverterInputCurrent: number;
  solarPanelCurrent: number;
  solarPanelGeneratedEnergy: number;
  solarPanelPower: number;
  solarPanelTemperature: number;
  solarPanelVoltage: number;
  windTurbineCurrent: number;
  windTurbineGeneratedEnergy: number;
  windTurbinePower: number;
  windTurbineRevolutions: number;
  windTurbineVoltage: number;
  inputSolarRadiation1?: number;
  inputSolarRadiation2?: number;
  inputWindSpeed?: number;
  inputAlternCurrentLoadPower?: number;
  inputAlternCurrentLoadPowerFactor?: number;
  inputDirectCurrentLoadPower?: number;
};

export type SolarWindOutputHistoric = CommonGraphType & {
  monocrystallinePanelTemperature: number[];
  policrystallinePanelTemperature: number[];
  flexPanelTemperature: number[];
  cadmiumTelluridePanelTemperature: number[];
  batteryCurrent: number[];
  batteryPower: number[];
  batteryStateOfCharge: number[];
  batteryTemperature: number[];
  batteryVoltage: number[];
  chargeCycle: number[];
  controllerPower: number[];
  controllerCurrent: number[];
  directCurrentLoadVoltage: number[];
  directCurrentVoltage: number[];
  directCurrentLoadPower: number[];
  directCurrentLoadCurrent: number[];
  externalGridVoltage: number[];
  externalGridPower: number[];
  externalGridState: number[];
  externalGridCurrent: number[];
  hybridInverterActivePower: number[];
  hybridInverterApparentPower: number[];
  hybridInverterOutputCurrent: number[];
  hybridInverterReactivePower: number[];
  hybridInverterVoltage: number[];
  inverterActivePower: number[];
  inverterApparentPower: number[];
  inverterOutputCurrent: number[];
  inverterReactivePower: number[];
  inverterVoltage: number[];
  inverterInputPower: number[];
  inverterState: boolean[];
  inverterInputCurrent: number[];
  solarPanelCurrent: number[];
  solarPanelGeneratedEnergy: number[];
  solarPanelPower: number[];
  solarPanelTemperature: number[];
  solarPanelVoltage: number[];
  windTurbineCurrent: number[];
  windTurbineGeneratedEnergy: number[];
  windTurbinePower: number[];
  windTurbineRevolutions: number[];
  windTurbineVoltage: number[];
};

export const SOLAR_WIND: SolarWindParameters = {
  name: 'Nombre',
  queryTime: Config.QUERY_TIME_OFFLINE,
  disableParameters: false,
  timeMultiplier: {
    disabled: false,
    value: 1,
    tooltip: 'Multiplicador de tiempo',
    unit: '',
    variableString: '',
    min: 1,
    max: 60,
  },
  inputOfflineOperation: true,
  inputOperationMode: OperationModeType.Mode1,
  monocrystallinePanel: MONOCRYSTALLINE_PANEL,
  policrystallinePanel: POLICRYSTALLINE_PANEL,
  flexPanel: FLEX_PANEL,
  cadmiumTelluridePanel: CADMIUM_TELLURIDE_PANEL,
  windTurbine: WIND_TURBINE,
  battery1: BATTERY,
  isBattery2: false,
  battery2: BATTERY,
  controller: CONTROLLER,
  offgridInverter: OFFGRID_INVERTER,
  hybridInverter: HYBRID_INVERTER,
  solarRadiation1: {
    disabled: false,
    value: 800,
    tooltip: 'Radiación solar 1',
    unit: 'W / m²',
    variableString: 'Radiación solar 1',
    min: 0,
    max: 1500,
    step: 100,
  },
  solarRadiation2: {
    disabled: false,
    value: 800,
    tooltip: 'Radiación solar 2',
    unit: 'W / m²',
    variableString: 'Radiación solar 2',
    min: 0,
    max: 1500,
    step: 100,
  },
  temperature: {
    disabled: false,
    value: 25,
    tooltip: 'Temperatura ambiente',
    unit: '°C',
    variableString: 'Temperatura ambiente',
    min: -10,
    max: 50,
  },
  windSpeed: {
    disabled: false,
    value: 10,
    tooltip: 'Velocidad del viento',
    unit: 'm / s',
    variableString: 'Velocidad del viento',
    min: 0,
    max: 70,
  },
  windDensity: {
    disabled: false,
    value: 1.12,
    tooltip: 'Densidad del aire',
    unit: 'kg / m³',
    variableString: 'Densidad del aire',
    min: 0.8,
    max: 1.5,
    step: 0.01,
  },
  alternCurrentLoadPower: {
    disabled: false,
    value: 200,
    tooltip: 'Potencia de la carga de alterna',
    unit: 'W',
    variableString: 'Potencia',
    min: 0,
    max: 2000,
    step: 100,
  },
  alternCurrentLoadPowerFactor: {
    disabled: false,
    value: 1,
    tooltip: 'Factor de potencia de la carga de alterna',
    unit: '',
    variableString: 'Factor de potencia',
    min: -1,
    max: 1,
    step: 0.1,
  },
  directCurrentLoadPower: {
    disabled: false,
    value: 200,
    tooltip: 'Potencia de la carga de directa',
    unit: 'W',
    variableString: 'Potencia',
    min: 0,
    max: 2000,
    step: 100,
  },
  externalGridState: false,
};

export const MODE_1_CADMIO_MODE_2: DiagramVariableType[] = [
  {
    name: 'Potencia carga CA',
    variable: 'alternCurrentLoadPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 0,
    x: 3200,
    y: 1680,
  },
  {
    name: 'Factor de potencia carga CA',
    variable: 'alternCurrentLoadPowerFactor',
    unit: '',
    isShown: true,
    diagramName: 'FP',
    fixed: 2,
    x: 3200,
    y: 1760,
  },
  {
    name: 'Estado de carga baterías',
    variable: 'batteryStateOfCharge',
    unit: '%',
    isShown: true,
    diagramName: 'SOC',
    fixed: 3,
    x: 1350,
    y: 180,
  },
  {
    name: 'Potencia batería',
    variable: 'batteryPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1350,
    y: 260,
  },
  {
    name: 'Voltaje baterías',
    variable: 'batteryVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 3,
    x: 1350,
    y: 340,
  },
  {
    name: 'Corriente baterías',
    variable: 'batteryCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1350,
    y: 420,
  },
  {
    name: 'Temperatura baterías',
    variable: 'batteryTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'Temperatura',
    fixed: 1,
    x: 1350,
    y: 500,
    hasAdditionalCondition: 0,
  },
  {
    name: 'Temperatura panel monocristalino',
    variable: 'monocrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. mono',
    fixed: 1,
    x: 980,
    y: 2060,
    hasAdditionalCondition: 1,
  },
  {
    name: 'Temperatura panel policristalino',
    variable: 'policrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. poli',
    fixed: 1,
    x: 980,
    y: 2140,
    hasAdditionalCondition: 2,
  },
  {
    name: 'Temperatura panel flexible',
    variable: 'flexPanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. flexible',
    fixed: 1,
    x: 980,
    y: 2220,
    hasAdditionalCondition: 3,
  },
  {
    name: 'Temperatura panel Telururo de Cadmio',
    variable: 'cadmiumTelluridePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. Cadmio',
    fixed: 1,
    x: 980,
    y: 2300,
    hasAdditionalCondition: 4,
  },
  {
    name: 'Potencia controlador',
    variable: 'controllerPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1960,
    y: 1450,
  },
  {
    name: 'Voltaje corriente directa',
    variable: 'directCurrentVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 1960,
    y: 1530,
  },
  {
    name: 'Corriente controlador',
    variable: 'controllerCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1960,
    y: 1610,
  },
  {
    name: 'Potencia carga CD',
    variable: 'directCurrentLoadPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1920,
    y: 1880,
  },
  {
    name: 'Voltaje carga CD',
    variable: 'directCurrentLoadVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 1920,
    y: 1960,
  },
  {
    name: 'Corriente carga CD',
    variable: 'directCurrentLoadCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1920,
    y: 2040,
  },
  {
    name: 'Potencia aparente inversor',
    variable: 'inverterApparentPower',
    unit: 'VA',
    isShown: true,
    diagramName: 'P. aparente',
    fixed: 1,
    x: 3200,
    y: 1020,
  },
  {
    name: 'Potencia activa inversor',
    variable: 'inverterActivePower',
    unit: 'W',
    isShown: true,
    diagramName: 'P. activa',
    fixed: 1,
    x: 3200,
    y: 1100,
  },
  {
    name: 'Potencia reactiva inversor',
    variable: 'inverterReactivePower',
    unit: 'var',
    isShown: true,
    diagramName: 'P. reactiva',
    fixed: 1,
    x: 3200,
    y: 1180,
  },
  {
    name: 'Voltaje inversor',
    variable: 'inverterVoltage',
    unit: 'Vca',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 3200,
    y: 1260,
  },
  {
    name: 'Corriente inversor',
    variable: 'inverterOutputCurrent',
    unit: 'Aca',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 3200,
    y: 1340,
  },
  {
    name: 'Potencia entrada inversor',
    variable: 'inverterInputPower',
    unit: 'W',
    isShown: true,
    diagramName: 'P. entrada',
    fixed: 1,
    x: 3200,
    y: 540,
  },
  {
    name: 'Corriente entrada inversor',
    variable: 'inverterInputCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'I entrada',
    fixed: 1,
    x: 3200,
    y: 620,
  },
  {
    name: 'Estado inversor',
    variable: 'inverterState',
    unit: '',
    isShown: true,
    diagramName: 'Estado',
    fixed: 0,
    x: 3200,
    y: 700,
  },
  {
    name: 'Potencia paneles solares',
    variable: 'solarPanelPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 160,
    y: 2080,
  },
  {
    name: 'Voltaje paneles solares',
    variable: 'solarPanelVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 160,
    y: 2160,
  },
  {
    name: 'Corriente paneles solares',
    variable: 'solarPanelCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 160,
    y: 2240,
  },
];

export const MODE_1_MODE_3: DiagramVariableType[] = [
  {
    name: 'Estado de carga baterías',
    variable: 'batteryStateOfCharge',
    unit: '%',
    isShown: true,
    diagramName: 'SOC',
    fixed: 3,
    x: 1650,
    y: 180,
  },
  {
    name: 'Potencia batería',
    variable: 'batteryPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1650,
    y: 260,
  },
  {
    name: 'Voltaje baterías',
    variable: 'batteryVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 3,
    x: 1650,
    y: 340,
  },
  {
    name: 'Corriente baterías',
    variable: 'batteryCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1650,
    y: 420,
  },
  {
    name: 'Temperatura baterías',
    variable: 'batteryTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'Temperatura',
    fixed: 1,
    x: 1650,
    y: 500,
    hasAdditionalCondition: 0,
  },
  {
    name: 'Temperatura panel monocristalino',
    variable: 'monocrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. mono',
    fixed: 1,
    x: 1280,
    y: 2060,
    hasAdditionalCondition: 1,
  },
  {
    name: 'Temperatura panel policristalino',
    variable: 'policrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. poli',
    fixed: 1,
    x: 1280,
    y: 2140,
    hasAdditionalCondition: 2,
  },
  {
    name: 'Temperatura panel flexible',
    variable: 'flexPanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. flexible',
    fixed: 1,
    x: 1280,
    y: 2220,
    hasAdditionalCondition: 3,
  },
  {
    name: 'Temperatura panel Telururo de Cadmio',
    variable: 'cadmiumTelluridePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. Cadmio',
    fixed: 1,
    x: 1280,
    y: 2300,
    hasAdditionalCondition: 4,
  },
  {
    name: 'Potencia controlador',
    variable: 'controllerPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2260,
    y: 1450,
  },
  {
    name: 'Voltaje corriente directa',
    variable: 'directCurrentVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 2260,
    y: 1530,
  },
  {
    name: 'Corriente controlador',
    variable: 'controllerCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2260,
    y: 1610,
  },
  {
    name: 'Potencia carga CD',
    variable: 'directCurrentLoadPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2220,
    y: 1880,
  },
  {
    name: 'Voltaje carga CD',
    variable: 'directCurrentLoadVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 2220,
    y: 1960,
  },
  {
    name: 'Corriente carga CD',
    variable: 'directCurrentLoadCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2220,
    y: 2040,
  },
  {
    name: 'Potencia paneles solares',
    variable: 'solarPanelPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 460,
    y: 2080,
  },
  {
    name: 'Voltaje paneles solares',
    variable: 'solarPanelVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 460,
    y: 2160,
  },
  {
    name: 'Corriente paneles solares',
    variable: 'solarPanelCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 460,
    y: 2240,
  },
];

export const MODE_2_HYBRID_DIAGRAM_VARIABLES: DiagramVariableType[] = [
  {
    name: 'Potencia carga CA',
    variable: 'alternCurrentLoadPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 0,
    x: 3050,
    y: 1300,
  },
  {
    name: 'Factor de potencia carga CA',
    variable: 'alternCurrentLoadPowerFactor',
    unit: '',
    isShown: true,
    diagramName: 'FP',
    fixed: 2,
    x: 3050,
    y: 1380,
  },
  {
    name: 'Estado de carga baterías',
    variable: 'batteryStateOfCharge',
    unit: '%',
    isShown: true,
    diagramName: 'SOC',
    fixed: 3,
    x: 3050,
    y: 1820,
  },
  {
    name: 'Potencia batería',
    variable: 'batteryPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 3050,
    y: 1900,
  },
  {
    name: 'Voltaje baterías',
    variable: 'batteryVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 3,
    x: 3050,
    y: 1980,
  },
  {
    name: 'Corriente baterías',
    variable: 'batteryCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 3050,
    y: 2060,
  },
  {
    name: 'Temperatura baterías',
    variable: 'batteryTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'Temperatura',
    fixed: 1,
    x: 3050,
    y: 3140,
    hasAdditionalCondition: 0,
  },
  {
    name: 'Temperatura panel monocristalino',
    variable: 'monocrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. mono',
    fixed: 1,
    x: 200,
    y: 1020,
    hasAdditionalCondition: 1,
  },
  {
    name: 'Temperatura panel policristalino',
    variable: 'policrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. poli',
    fixed: 1,
    x: 200,
    y: 1100,
    hasAdditionalCondition: 2,
  },
  {
    name: 'Temperatura panel flexible',
    variable: 'flexPanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. flexible',
    fixed: 1,
    x: 200,
    y: 1180,
    hasAdditionalCondition: 3,
  },
  {
    name: 'Temperatura panel Telururo de Cadmio',
    variable: 'cadmiumTelluridePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. Cadmio',
    fixed: 1,
    x: 200,
    y: 1260,
    hasAdditionalCondition: 4,
  },
  {
    name: 'Potencia red externa',
    variable: 'externalGridPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 200,
    y: 1800,
  },
  {
    name: 'Voltaje red externa',
    variable: 'externalGridVoltage',
    unit: 'Vca',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 200,
    y: 1880,
  },
  {
    name: 'Corriente red externa',
    variable: 'externalGridCurrent',
    unit: 'Aca',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 200,
    y: 1960,
  },
  {
    name: 'Estado red externa',
    variable: 'externalGridState',
    unit: '',
    isShown: true,
    diagramName: 'Estado',
    fixed: 0,
    x: 200,
    y: 2040,
  },
  {
    name: 'Potencia aparente inversor híbrido',
    variable: 'hybridInverterApparentPower',
    unit: 'VA',
    isShown: true,
    diagramName: 'P. aparente',
    fixed: 1,
    x: 3050,
    y: 520,
  },
  {
    name: 'Potencia activa inversor híbrido',
    variable: 'hybridInverterActivePower',
    unit: 'W',
    isShown: true,
    diagramName: 'P. activa',
    fixed: 1,
    x: 3050,
    y: 600,
  },
  {
    name: 'Potencia reactiva inversor híbrido',
    variable: 'hybridInverterReactivePower',
    unit: 'var',
    isShown: true,
    diagramName: 'P. reactiva',
    fixed: 1,
    x: 3050,
    y: 680,
  },
  {
    name: 'Voltaje inversor híbrido',
    variable: 'hybridInverterVoltage',
    unit: 'Vca',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 3050,
    y: 760,
  },
  {
    name: 'Corriente inversor híbrido',
    variable: 'hybridInverterOutputCurrent',
    unit: 'Aca',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 3050,
    y: 840,
  },
  {
    name: 'Potencia paneles solares',
    variable: 'solarPanelPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 900,
    y: 1140,
  },
  {
    name: 'Voltaje paneles solares',
    variable: 'solarPanelVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 900,
    y: 1220,
  },
  {
    name: 'Corriente paneles solares',
    variable: 'solarPanelCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 900,
    y: 1300,
  },
  {
    name: 'Corriente paneles solares',
    variable: 'directCurrentVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 1700,
    y: 1600,
  },
];

export const MODE_4: DiagramVariableType[] = [
  {
    name: 'Estado de carga baterías',
    variable: 'batteryStateOfCharge',
    unit: '%',
    isShown: true,
    diagramName: 'SOC',
    fixed: 3,
    x: 1650,
    y: 180,
  },
  {
    name: 'Potencia batería',
    variable: 'batteryPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1650,
    y: 260,
  },
  {
    name: 'Voltaje baterías',
    variable: 'batteryVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 3,
    x: 1650,
    y: 340,
  },
  {
    name: 'Corriente baterías',
    variable: 'batteryCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1650,
    y: 420,
  },
  {
    name: 'Temperatura baterías',
    variable: 'batteryTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'Temperatura',
    fixed: 1,
    x: 1650,
    y: 500,
    hasAdditionalCondition: 0,
  },
  {
    name: 'Potencia controlador',
    variable: 'controllerPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2260,
    y: 1450,
  },
  {
    name: 'Voltaje corriente directa',
    variable: 'directCurrentVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 2260,
    y: 1530,
  },
  {
    name: 'Corriente controlador',
    variable: 'controllerCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2260,
    y: 1610,
  },
  {
    name: 'Potencia carga CD',
    variable: 'directCurrentLoadPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2220,
    y: 1880,
  },
  {
    name: 'Voltaje carga CD',
    variable: 'directCurrentLoadVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 2220,
    y: 1960,
  },
  {
    name: 'Corriente carga CD',
    variable: 'directCurrentLoadCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2220,
    y: 2040,
  },
  {
    name: 'Potencia turbina',
    variable: 'windTurbinePower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1120,
    y: 1040,
  },
  {
    name: 'Voltaje turbina',
    variable: 'windTurbineVoltage',
    unit: 'Vca',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 1120,
    y: 1120,
  },
  {
    name: 'Corriente turbina',
    variable: 'windTurbineCurrent',
    unit: 'Aca',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1120,
    y: 1200,
  },
  {
    name: 'Revoluciones turbina',
    variable: 'windTurbineRevolutions',
    unit: 'r/min',
    isShown: true,
    diagramName: 'Revoluciones',
    fixed: 1,
    x: 1120,
    y: 1280,
    hasAdditionalCondition: 0,
  },
];

export const MODE_5: DiagramVariableType[] = [
  {
    name: 'Estado de carga baterías',
    variable: 'batteryStateOfCharge',
    unit: '%',
    isShown: true,
    diagramName: 'SOC',
    fixed: 3,
    x: 1650,
    y: 180,
  },
  {
    name: 'Potencia batería',
    variable: 'batteryPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1650,
    y: 260,
  },
  {
    name: 'Voltaje baterías',
    variable: 'batteryVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 3,
    x: 1650,
    y: 340,
  },
  {
    name: 'Corriente baterías',
    variable: 'batteryCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1650,
    y: 420,
  },
  {
    name: 'Temperatura baterías',
    variable: 'batteryTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'Temperatura',
    fixed: 1,
    x: 1650,
    y: 500,
    hasAdditionalCondition: 0,
  },
  {
    name: 'Temperatura panel monocristalino',
    variable: 'monocrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. mono',
    fixed: 1,
    x: 1280,
    y: 2060,
    hasAdditionalCondition: 1,
  },
  {
    name: 'Temperatura panel policristalino',
    variable: 'policrystallinePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. poli',
    fixed: 1,
    x: 1280,
    y: 2140,
    hasAdditionalCondition: 2,
  },
  {
    name: 'Temperatura panel flexible',
    variable: 'flexPanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. flexible',
    fixed: 1,
    x: 1280,
    y: 2220,
    hasAdditionalCondition: 3,
  },
  {
    name: 'Temperatura panel Telururo de Cadmio',
    variable: 'cadmiumTelluridePanelTemperature',
    unit: '°C',
    isShown: true,
    diagramName: 'T. Cadmio',
    fixed: 1,
    x: 1280,
    y: 2300,
    hasAdditionalCondition: 4,
  },
  {
    name: 'Potencia controlador',
    variable: 'controllerPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2260,
    y: 1450,
  },
  {
    name: 'Voltaje corriente directa',
    variable: 'directCurrentVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 2260,
    y: 1530,
  },
  {
    name: 'Corriente controlador',
    variable: 'controllerCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2260,
    y: 1610,
  },
  {
    name: 'Potencia carga CD',
    variable: 'directCurrentLoadPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 2220,
    y: 1880,
  },
  {
    name: 'Voltaje carga CD',
    variable: 'directCurrentLoadVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 2220,
    y: 1960,
  },
  {
    name: 'Corriente carga CD',
    variable: 'directCurrentLoadCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 2220,
    y: 2040,
  },
  {
    name: 'Potencia paneles solares',
    variable: 'solarPanelPower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 460,
    y: 2080,
  },
  {
    name: 'Voltaje paneles solares',
    variable: 'solarPanelVoltage',
    unit: 'Vcd',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 2,
    x: 460,
    y: 2160,
  },
  {
    name: 'Corriente paneles solares',
    variable: 'solarPanelCurrent',
    unit: 'Acd',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 460,
    y: 2240,
  },
  {
    name: 'Potencia turbina',
    variable: 'windTurbinePower',
    unit: 'W',
    isShown: true,
    diagramName: 'Potencia',
    fixed: 1,
    x: 1120,
    y: 1040,
  },
  {
    name: 'Voltaje turbina',
    variable: 'windTurbineVoltage',
    unit: 'Vca',
    isShown: true,
    diagramName: 'Voltaje',
    fixed: 1,
    x: 1120,
    y: 1120,
  },
  {
    name: 'Corriente turbina',
    variable: 'windTurbineCurrent',
    unit: 'Aca',
    isShown: true,
    diagramName: 'Corriente',
    fixed: 1,
    x: 1120,
    y: 1200,
  },
  {
    name: 'Revoluciones turbina',
    variable: 'windTurbineRevolutions',
    unit: 'r/min',
    isShown: true,
    diagramName: 'Revoluciones',
    fixed: 1,
    x: 1120,
    y: 1280,
    hasAdditionalCondition: 0,
  },
];
