version: '2'

networks:
  laboratorio-default:
    driver: bridge

services:
  influxdb:
    image: influxdb
    ports:
      - '8086:8086'
    hostname: influxdb
    container_name: influxdb
    volumes:
      - influxdb-storage-data:/var/lib/influxdb2
      - influxdb-storage-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    restart: always
    networks:
      - laboratorio-default

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - '3001:3000'
    hostname: grafana
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,yesoreyeram-boomtheme-panel
      - GF_SECURITY_ALLOW_EMBEDDING=true
    networks:
      - laboratorio-default

volumes:
  influxdb-storage-data:
  influxdb-storage-config:
  grafana-storage:
