{
 "title": "Módulo Solar-Eólico",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sistema Autónomo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Proceso",
     "type": "canvas",
     "gridPos": { "h": 25, "w": 20, "x": 0, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Módulo de turbinas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ED001\" or r[\"_field\"] == \"EG001\" or r[\"_field\"] == \"EI001\" or r[\"_field\"] == \"FIT001\" or r[\"_field\"] == \"FP001\" or r[\"_field\"] == \"IAC001\" or r[\"_field\"] == \"IC001\" or r[\"_field\"] == \"IC002\" or r[\"_field\"] == \"IG001\" or r[\"_field\"] == \"IG002\" or r[\"_field\"] == \"LEH001\" or r[\"_field\"] == \"LEL001\" or r[\"_field\"] == \"PB001\" or r[\"_field\"] == \"PB002\" or r[\"_field\"] == \"PG001\" or r[\"_field\"] == \"PKVA001\" or r[\"_field\"] == \"PG002\" or r[\"_field\"] == \"PKVAR001\" or r[\"_field\"] == \"PKW001\" or r[\"_field\"] == \"PT001\" or r[\"_field\"] == \"PT002\" or r[\"_field\"] == \"TE001\" or r[\"_field\"] == \"TE002\" or r[\"_field\"] == \"TE003\" or r[\"_field\"] == \"TE004\" or r[\"_field\"] == \"VAC001\" or r[\"_field\"] == \"VB001\" or r[\"_field\"] == \"VB002\" or r[\"_field\"] == \"VBU001\" or r[\"_field\"] == \"VCH001\" or r[\"_field\"] == \"VDF001\" or r[\"_field\"] == \"VDN001\" or r[\"_field\"] == \"VFL001\" or r[\"_field\"] == \"VG001\" or r[\"_field\"] == \"VG002\")"
      }
     ]
    },
    {
     "title": "Turbina Pelton",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Módulo de turbinas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PG001\")"
      }
     ]
    },
    {
     "title": "Turbina Turgo",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Módulo de turbinas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PG002\")"
      }
     ]
    },
    {
     "title": "Baterías",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Módulo de turbinas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"VB001\")"
      }
     ]
    },
    {
     "title": "Baterías",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Módulo de turbinas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TE003\")"
      }
     ]
    },
    {
     "title": "Carga",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Módulo de turbinas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PKW001\")"
      }
     ]
    },
    {
     "title": "Pelton",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Módulo de turbinas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"FIT001\" or r[\"_field\"] == \"PT001\" or r[\"_field\"] == \"VG002\" or r[\"_field\"] == \"IG002\" or r[\"_field\"] == \"PG002\")"
      }
     ]
    },
    {
     "title": "Turgo",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Módulo de turbinas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"FIT001\" or r[\"_field\"] == \"PT001\" or r[\"_field\"] == \"VG001\" or r[\"_field\"] == \"IG001\" or r[\"_field\"] == \"PG001\")"
      }
     ]
    },
    {
     "title": "Baterías",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Módulo de turbinas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"VB001\" or r[\"_field\"] == \"IC001\" or r[\"_field\"] == \"TE003\")"
      }
     ]
    },
    {
     "title": "Carga",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Módulo de turbinas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"VAC001\" or r[\"_field\"] == \"IAC001\" or r[\"_field\"] == \"PKVA001\" or r[\"_field\"] == \"PKVAR001\" or r[\"_field\"] == \"FP001\" or r[\"_field\"] == \"PKW001\")"
      }
     ]
    },
    {
     "title": "Variables",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Módulo de turbinas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"FIT001\" or r[\"_field\"] == \"PT001\" or r[\"_field\"] == \"VG001\" or r[\"_field\"] == \"IG001\" or r[\"_field\"] == \"PG001\" or r[\"_field\"] == \"VB001\" or r[\"_field\"] == \"IC001\" or r[\"_field\"] == \"TE001\" or r[\"_field\"] == \"VAC001\" or r[\"_field\"] == \"IAC001\" or r[\"_field\"] == \"PKVA001\" or r[\"_field\"] == \"PKVAR001\" or r[\"_field\"] == \"FP001\" or r[\"_field\"] == \"PKW001\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Sistema Híbrido",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true
  }
 ]
}