{
 "title": "Tablero Eléctrico",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TP_Totalizador",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voltajes LN",
     "type": "gauge",
     "gridPos": { "h": 15, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1 Voltaje\" or r[\"_field\"] == \"L2 Voltaje\" or r[\"_field\"] == \"L3 Voltaje\")"
      }
     ]
    },
    {
     "title": "Voltajes LL",
     "type": "gauge",
     "gridPos": { "h": 15, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1-L2 Voltaje\" or r[\"_field\"] == \"L2-L3 Voltaje\" or r[\"_field\"] == \"L3-L1 Voltaje\")"
      }
     ]
    },
    {
     "title": "Corrientes",
     "type": "gauge",
     "gridPos": { "h": 15, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1 Corriente\" or r[\"_field\"] == \"L2 Corriente\" or r[\"_field\"] == \"L3 Corriente\")"
      }
     ]
    },
    {
     "title": "Potencia activa",
     "type": "gauge",
     "gridPos": { "h": 15, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1 Potencia Activa\" or r[\"_field\"] == \"L2 Potencia Activa\" or r[\"_field\"] == \"L3 Potencia Activa\")"
      }
     ]
    },
    {
     "title": "Potencia reactiva",
     "type": "gauge",
     "gridPos": { "h": 15, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "kvoltampreact" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1 Potencia Reactiva\" or r[\"_field\"] == \"L2 Potencia Reactiva\" or r[\"_field\"] == \"L3 Potencia Reactiva\")"
      }
     ]
    },
    {
     "title": "Potencia aparente",
     "type": "gauge",
     "gridPos": { "h": 15, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1 Potencia Aparente\" or r[\"_field\"] == \"L2 Potencia Aparente\" or r[\"_field\"] == \"L3 Potencia Aparente\")"
      }
     ]
    },
    {
     "title": "Factor de potencia",
     "type": "gauge",
     "gridPos": { "h": 15, "w": 3, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1 Factor de Potencia\" or r[\"_field\"] == \"L2 Factor de Potencia\" or r[\"_field\"] == \"L3 Factor de Potencia\")"
      }
     ]
    },
    {
     "title": "Frecuencia",
     "type": "gauge",
     "gridPos": { "h": 15, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Frecuencia\")"
      }
     ]
    },
    {
     "title": "THD voltaje",
     "type": "gauge",
     "gridPos": { "h": 15, "w": 3, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1 THD Voltaje\" or r[\"_field\"] == \"L2 THD Voltaje\" or r[\"_field\"] == \"L3 THD Voltaje\")"
      }
     ]
    },
    {
     "title": "Armónicos de voltaje L1",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 7, "x": 3, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1 Armónico Voltaje 02\" or r[\"_field\"] == \"L1 Armónico Voltaje 03\" or r[\"_field\"] == \"L1 Armónico Voltaje 04\" or r[\"_field\"] == \"L1 Armónico Voltaje 05\" or r[\"_field\"] == \"L1 Armónico Voltaje 06\" or r[\"_field\"] == \"L1 Armónico Voltaje 07\" or r[\"_field\"] == \"L1 Armónico Voltaje 08\" or r[\"_field\"] == \"L1 Armónico Voltaje 09\" or r[\"_field\"] == \"L1 Armónico Voltaje 10\" or r[\"_field\"] == \"L1 Armónico Voltaje 11\" or r[\"_field\"] == \"L1 Armónico Voltaje 12\" or r[\"_field\"] == \"L1 Armónico Voltaje 13\" or r[\"_field\"] == \"L1 Armónico Voltaje 14\" or r[\"_field\"] == \"L1 Armónico Voltaje 15\")"
      }
     ]
    },
    {
     "title": "Armónicos de voltaje L2",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 7, "x": 10, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L2 Armónico Voltaje 02\" or r[\"_field\"] == \"L2 Armónico Voltaje 03\" or r[\"_field\"] == \"L2 Armónico Voltaje 04\" or r[\"_field\"] == \"L2 Armónico Voltaje 05\" or r[\"_field\"] == \"L2 Armónico Voltaje 06\" or r[\"_field\"] == \"L2 Armónico Voltaje 07\" or r[\"_field\"] == \"L2 Armónico Voltaje 08\" or r[\"_field\"] == \"L2 Armónico Voltaje 09\" or r[\"_field\"] == \"L2 Armónico Voltaje 10\" or r[\"_field\"] == \"L2 Armónico Voltaje 11\" or r[\"_field\"] == \"L2 Armónico Voltaje 12\" or r[\"_field\"] == \"L2 Armónico Voltaje 13\" or r[\"_field\"] == \"L2 Armónico Voltaje 14\" or r[\"_field\"] == \"L2 Armónico Voltaje 15\")"
      }
     ]
    },
    {
     "title": "Armónicos de voltaje L3",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 7, "x": 17, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L3 Armónico Voltaje 02\" or r[\"_field\"] == \"L3 Armónico Voltaje 03\" or r[\"_field\"] == \"L3 Armónico Voltaje 04\" or r[\"_field\"] == \"L3 Armónico Voltaje 05\" or r[\"_field\"] == \"L3 Armónico Voltaje 06\" or r[\"_field\"] == \"L3 Armónico Voltaje 07\" or r[\"_field\"] == \"L3 Armónico Voltaje 08\" or r[\"_field\"] == \"L3 Armónico Voltaje 09\" or r[\"_field\"] == \"L3 Armónico Voltaje 10\" or r[\"_field\"] == \"L3 Armónico Voltaje 11\" or r[\"_field\"] == \"L3 Armónico Voltaje 12\" or r[\"_field\"] == \"L3 Armónico Voltaje 13\" or r[\"_field\"] == \"L3 Armónico Voltaje 14\" or r[\"_field\"] == \"L3 Armónico Voltaje 15\")"
      }
     ]
    },
    {
     "title": "THD corriente",
     "type": "gauge",
     "gridPos": { "h": 15, "w": 3, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1 THD Corriente\" or r[\"_field\"] == \"L2 THD Corriente\" or r[\"_field\"] == \"L3 THD Corriente\")"
      }
     ]
    },
    {
     "title": "Armónicos de corriente L1",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 7, "x": 3, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1 Armónico Corriente 02\" or r[\"_field\"] == \"L1 Armónico Corriente 03\" or r[\"_field\"] == \"L1 Armónico Corriente 04\" or r[\"_field\"] == \"L1 Armónico Corriente 05\" or r[\"_field\"] == \"L1 Armónico Corriente 06\" or r[\"_field\"] == \"L1 Armónico Corriente 07\" or r[\"_field\"] == \"L1 Armónico Corriente 08\" or r[\"_field\"] == \"L1 Armónico Corriente 09\" or r[\"_field\"] == \"L1 Armónico Corriente 10\" or r[\"_field\"] == \"L1 Armónico Corriente 11\" or r[\"_field\"] == \"L1 Armónico Corriente 12\" or r[\"_field\"] == \"L1 Armónico Corriente 13\" or r[\"_field\"] == \"L1 Armónico Corriente 14\" or r[\"_field\"] == \"L1 Armónico Corriente 15\")"
      }
     ]
    },
    {
     "title": "Armónicos de corriente L2",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 7, "x": 10, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L2 Armónico Corriente 02\" or r[\"_field\"] == \"L2 Armónico Corriente 03\" or r[\"_field\"] == \"L2 Armónico Corriente 04\" or r[\"_field\"] == \"L2 Armónico Corriente 05\" or r[\"_field\"] == \"L2 Armónico Corriente 06\" or r[\"_field\"] == \"L2 Armónico Corriente 07\" or r[\"_field\"] == \"L2 Armónico Corriente 08\" or r[\"_field\"] == \"L2 Armónico Corriente 09\" or r[\"_field\"] == \"L2 Armónico Corriente 10\" or r[\"_field\"] == \"L2 Armónico Corriente 11\" or r[\"_field\"] == \"L2 Armónico Corriente 12\" or r[\"_field\"] == \"L2 Armónico Corriente 13\" or r[\"_field\"] == \"L2 Armónico Corriente 14\" or r[\"_field\"] == \"L2 Armónico Corriente 15\")"
      }
     ]
    },
    {
     "title": "Armónicos de corriente L3",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 7, "x": 17, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L3 Armónico Corriente 02\" or r[\"_field\"] == \"L3 Armónico Corriente 03\" or r[\"_field\"] == \"L3 Armónico Corriente 04\" or r[\"_field\"] == \"L3 Armónico Corriente 05\" or r[\"_field\"] == \"L3 Armónico Corriente 06\" or r[\"_field\"] == \"L3 Armónico Corriente 07\" or r[\"_field\"] == \"L3 Armónico Corriente 08\" or r[\"_field\"] == \"L3 Armónico Corriente 09\" or r[\"_field\"] == \"L3 Armónico Corriente 10\" or r[\"_field\"] == \"L3 Armónico Corriente 11\" or r[\"_field\"] == \"L3 Armónico Corriente 12\" or r[\"_field\"] == \"L3 Armónico Corriente 13\" or r[\"_field\"] == \"L3 Armónico Corriente 14\" or r[\"_field\"] == \"L3 Armónico Corriente 15\")"
      }
     ]
    },
    {
     "title": "Energía",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Total Energía Activa - Importación\" or r[\"_field\"] == \"Total Energía Activa - Exportación\" or r[\"_field\"] == \"Total Energía Reactiva - Importación\" or r[\"_field\"] == \"Total Energía Reactiva - Exportación\")"
      }
     ]
    },
    {
     "title": "Energía",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Laboratorio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TP_Totalizador\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Total Energía Activa - Exportación\" or r[\"_field\"] == \"Total Energía Activa - Importación\" or r[\"_field\"] == \"Total Energía Reactiva - Exportación\" or r[\"_field\"] == \"Total Energía Reactiva - Importación\" or r[\"_field\"] == \"Total Energía Aparente\")"
      }
     ]
    }
   ]
  },
  {
   "title": "TP_Sistema PBM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true
  },
  {
   "title": "TP_Analizador Biogás",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true
  },
  {
   "title": "TP_Planta de Biogás",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true
  },
  {
   "title": "TP_Tunel de viento - Potencia",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true
  },
  {
   "title": "TP_Ventilador sistema eólico",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true
  },
  {
   "title": "TP_Torre de enfriamiento",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true
  },
  {
   "title": "TP_Banco de trabajo turbinas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true
  },
  {
   "title": "TP_Tablero Paneles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "TP_Iluminación Área 3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "TP_Video Wall Smart Grid",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "TP_Iluminación Área 2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true
  },
  {
   "title": "TP_Video Controller Smart Grid",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true
  },
  {
   "title": "TP_Iluminación Área 1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true
  },
  {
   "title": "TP_Mesa Biogás Fotovoltaico",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true
  },
  {
   "title": "TP_Nevera Biogás",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "TP_Mesón Sala Biogás",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  },
  {
   "title": "TP_Tunel de viento - control",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "TP_Modulo fotovoltaico eólico",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  },
  {
   "title": "TP_Modulo control turbinas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true
  }
 ]
}